xgeekshq/split

backend/src/app.module.ts, backend/src/infrastructure/database/mongoose.module.ts, backend/src/libs/enum/team.roles.ts, backend/src/libs/validators/check-unique-users.ts, backend/src/modules/boards/dto/board.dto.ts, backend/src/modules/boards/schemas/board.schema.ts, backend/src/modules/teams/applications/create.team.application.ts, backend/src/modules/teams/applications/get.team.application.ts, backend/src/modules/teams/controller/team.controller.ts, backend/src/modules/teams/dto/team.dto.ts, backend/src/modules/teams/dto/team.user.dto.ts, backend/src/modules/teams/interfaces/applications/create.team.application.interface.ts, backend/src/modules/teams/interfaces/applications/get.team.application.interface.ts, backend/src/modules/teams/interfaces/services/create.team.service.interface.ts, backend/src/modules/teams/interfaces/services/get.team.service.interface.ts, backend/src/modules/teams/interfaces/types.ts, backend/src/modules/teams/providers.ts, backend/src/modules/teams/schemas/team.user.schema.ts, backend/src/modules/teams/schemas/teams.schema.ts, backend/src/modules/teams/services/create.team.service.ts, backend/src/modules/teams/services/get.team.service.ts, backend/src/modules/teams/teams.module.ts
Relates to #122
- Teams controller
- Teams and team users models and schemas
- Create team and team users service
- Get team service
- Board schema updated with a team prop
This pull request is intended to close #122
=> feat: team and team users

backend/src/modules/auth/shared/login.auth.ts, backend/src/modules/boards/services/create.board.service.ts, backend/src/modules/boards/services/delete.board.service.ts
Relates to #128
- Refactor delete board method to also delete the sub-boards and board users
This pull request is intendend to close #128
=> refactor: delete board

backend/src/modules/boards/services/get.board.service.ts, frontend/components/Primitives/AlertBox.tsx
- alert box button
- users now appear in the divided boards
=> refactor: alert-box and users

frontend/stitches.config.ts
Fixes #165 
- As requested, it's necessary change the background color to `#F4F7F8`
- > **Feedback:** "I updated the body background color in the mean time. Please check the new value. Thank you (smile)"
This PR closes #165
=> [FIX]: Change Background Color

frontend/components/Board/AddCardOrComment.tsx, frontend/components/Board/Column/Column.tsx, frontend/components/Board/Column/styles.tsx, frontend/components/Board/Header/styles.tsx, frontend/pages/boards/[boardId].tsx, frontend/styles/globals.tsx, frontend/styles/pages/boards/board.styles.tsx, package-lock.json
Relates to #182 
- Add scroll on board columns
- Set style by default for all scrolls on application
This PR closes #182
=> [FEATURE]: Universal Scroll Style

frontend/components/Boards/MyBoards.tsx, frontend/stitches.config.ts, frontend/styles/colors/primary.colors.ts, package-lock.json
Fixes #185 
- Change background color and update colors from design system
This PR closes #185
=> [FIX]: Background Color

frontend/components/CreateBoard/Configurations/BoardConfigurations.tsx, frontend/components/CreateBoard/TipBar.tsx, frontend/components/Sidebar/partials/Content/index.tsx, frontend/components/Sidebar/partials/Header/index.tsx, frontend/components/Sidebar/partials/Header/styles.tsx, frontend/package-lock.json, frontend/package.json, frontend/pages/boards/new.tsx, frontend/schema/schemaCreateBoardForm.tsx, frontend/styles/pages/boards/new.styles.tsx
**Relates to #198** 
Afther the **SPLIT MVP Sync** meeting, this is the improvements for the **Add New Board**:
This PR Closes #198
=> [FEATURE]: Add New Board Improvements 

frontend/components/Primitives/Toast.tsx
Relates to #210 
- toasts  dismiss by themselves
This pull request closes #210
=> [FEATURE]:Error toasts should dismiss

backend/src/modules/users/dto/create.user.dto.ts, frontend/components/Primitives/Input.tsx, frontend/components/auth/LoginForm/styles.tsx, frontend/components/auth/SignUp/RegisterForm.tsx, frontend/components/auth/SignUp/SignUpOptionsForm.tsx, frontend/pages/index.tsx, frontend/schema/schemaRegisterForm.tsx, frontend/styles/pages/auth.styles.tsx
relates to #216 
- Sign up -> SSO email detected -> Login button should say “Login with SSO”
- Sign up -> Adjust spacing between Login button , “OR” and change email link 
- Sign up -> Remove first name/ last name 3 char validation
- Forms -> Only validate and show validation errors when the field is out of focus
- Password field -> add help to the info label, just switching to red when validation goes wrong
- Hide terms and conditions checkbox
- After successful sign up go straight away to dashboard
This pull request closes #216
=> [FEATURE]: New register schema, helpertext update on form

.github/workflows/deploy_backend.yml, .github/workflows/deploy_frontend.yml
=> fix: workflows app name

backend/src/modules/boards/services/get.board.service.ts
- Handle exception when no boards are found
=> fix: get boards error

frontend/src/pages/404.tsx, frontend/src/pages/500.tsx
Fixes #231
- Fix the href of go back link in both error pages
This pull request closes #231
=> fix: error pages go back link

frontend/src/styles/pages/auth.styles.tsx
fix to form layout so it stays at a fixed position
=> [FIX]: Login Form Layout

backend/src/modules/users/dto/create.user.dto.ts, backend/test/auth/auth.controller.spec.ts, frontend/src/components/Primitives/Input.tsx, frontend/src/components/auth/LoginForm/styles.tsx, frontend/src/components/auth/SignUp/RegisterForm.tsx, frontend/src/components/auth/SignUp/SignUpOptionsForm.tsx, frontend/src/schema/schemaRegisterForm.tsx, frontend/src/styles/pages/auth.styles.tsx
Relates to #240 
- User Schema updated
- Register Form helpertext update and frontend schemas
- helpertext icon updated
- emails are all set to lowercase
This pull request closes #240
=> [FIX]: Register form 

frontend/src/components/Board/Header/index.tsx
Fixes #250 
Update link path of ``Go to main board`` button
This pull request closes #250
=> [FIX]: Error go to main board

backend/src/modules/azure/interfaces/services/cron.azure.service.interface.ts, backend/src/modules/azure/services/auth.azure.service.ts, backend/src/modules/azure/services/cron.azure.service.ts
Fixes #262 
- Remove cron job and request access token when is needed
This pull request closes #262
=> fix(azure-token): remove cron job to request a token

backend/src/modules/azure/services/cron.azure.service.ts, frontend/src/api/authService.tsx, frontend/src/hooks/useUser.tsx, frontend/src/hooks/useVotes.tsx
Fixes #241 
- Remove await from azure login method and use nextauth redirect 
This pull request closes #241
=> fix(azure-auth): login with azure method updated

frontend/src/components/CreateBoard/SubTeamsTab/TeamSubTeamsConfigurations.tsx, frontend/src/hooks/useCreateBoard.tsx
Fixes #254
- Added the error alert when when the team have less than 4 members
- Stopped the creation of multiple boards ( cause of the issue error ) when the team have less than 4 members
This pull request closes #254
=> [FIX]: Handling the minimum of users error

frontend/src/hooks/useCreateBoard.tsx
Fixes #273 
Fix ``canAdd`` function to disable button when is not possible to add more sub-boards
This pull request closes #273
=> [FIX]: Add Sub boards

frontend/src/pages/boards/[boardId].tsx
Fixes #291
- Move the alertbox inside the container 
This pull request closes #291
=> [FIX]: Sub-team AlertBox miss placed 

frontend/src/components/auth/LoginForm/index.tsx, frontend/src/components/auth/SignUp/SignUpOptionsForm.tsx
Fixes #252 
Fix pipeline error after merge #252:
```
./src/components/auth/LoginForm/index.tsx:40:33
Type error: Expected 0 arguments, but got 1.
38 | const setToastState = useSetRecoilState(toastState);
39 | const [loginErrorCode, setLoginErrorCode] = useState(-1);
> 40 | const { loginAzure } = useUser(setLoginErrorCode);
| ^
41 | const methods = useForm<LoginUser>({
42 | 		mode:'onBlur',
43 | 		reValidateMode:'onBlur',
```
=> [FIX]: Pipeline Error

frontend/src/components/Primitives/Avatar.tsx, frontend/src/hooks/useAvatarColor.tsx
Fixes #295 
- Fix Avatar properties
This pull request closes #295
=> [FIX]: Frontend Pipeline - Avatar properties

frontend/src/components/Board/Settings/index.tsx, frontend/src/components/CreateBoard/Configurations/BoardConfigurations.tsx
Fixes #298
- Removed the button style and is logic
This pull request closes #298
=> [FEATURE]: Remove "Option to post cards anonymously" from Board Settings

frontend/src/components/Board/Settings/index.tsx, frontend/src/pages/boards/[boardId].tsx, frontend/src/store/updateBoard/atoms/update-board.atom.tsx
Fixes #299
This pull request closes #299
=> [FEATURE]: add hide cards settings

frontend/src/components/Board/Settings/index.tsx
Fixes #310
- Added a condicional for the vote settings, for when isSubBoard is false on the db
This pull request closes #310
=> [FIX]: Remove Votes options from Board Settings on Sub-boards

backend/src/modules/users/dto/create.user.dto.ts, backend/src/modules/users/dto/reset-password.dto.ts, frontend/src/schema/schemaRegisterForm.tsx, frontend/src/schema/schemaResetPasswordForm.tsx
Fixes #311
- Changed the regex as mention in the issue
This pull request closes #311
=> [FIX]: Missing upper case validation on register user

backend/src/modules/boards/dto/board.dto.ts, backend/src/modules/boards/schemas/board.schema.ts, backend/src/modules/boards/services/update.board.service.ts, backend/src/modules/votes/services/create.vote.service.ts, backend/src/modules/votes/services/delete.vote.service.ts, frontend/src/components/Board/Settings/index.tsx, frontend/src/components/Primitives/Input.tsx, frontend/src/hooks/useCreateBoard.tsx, frontend/src/types/board/board.ts
Fixes #304
- The user can't input a number lower the actual maxVotes
This pull request closes #304
=> [FIX]: Extra votes left on card

frontend/src/hooks/useCreateBoard.tsx
Relates to #308
Fixes #324
- Added type form totalUsedVotes to useCreateBoard.tsx
This pull request closes #324
=> [FIX]: totalUsedVotes type error

frontend/src/hooks/useCreateBoard.tsx, frontend/src/store/createBoard/atoms/create-board.atom.tsx
Relates to #308
Fixes #326
- Added type for totalUsedVotes to useCreateBoard.tsx
- Added type for totalUsedVotes to create-board.atom-tsx
This pull request closes #326
=> Fix build errors

backend/src/modules/cards/services/delete.card.service.ts
Fixes #313 
- Change logic in order to return votes to users when a card is deleted.
This pull request closes #313
=> [FIX]: Deleting a card will not return votes to users

backend/src/modules/votes/services/delete.vote.service.ts
Relates to #278
Fixes 
-Fixed the remove vote from a card function
This pull request closes #278
=> [FIX]: Delete votes error

backend/src/modules/boards/services/delete.board.service.ts
Relates to  #277
Fixes
-Fixed the delete board function, previously it was not working in the live version.
This pull request closes #277
=> [FIX]: Delete Board Function

frontend/src/helper/board/transformBoard.tsx, frontend/src/hooks/useCards.tsx
Relates to #330
Tasks: Add/Delete Card and Merge cards
=> [FEATURE]: Optimistic Updates - Cards

frontend/src/helper/board/transformBoard.tsx, frontend/src/hooks/useComments.tsx
Relates to #330
Tasks: Add/Delete/Edit comments
=> [FEATURE]: Optimistic Updates - Comments

backend/src/modules/boards/services/get.board.service.ts, backend/src/modules/boards/services/update.board.service.ts, backend/src/modules/cards/dto/card.item.dto.ts, backend/src/modules/cards/interfaces/services/get.card.service.interface.ts, backend/src/modules/cards/schemas/card.item.schema.ts, backend/src/modules/cards/schemas/card.schema.ts, backend/src/modules/cards/services/create.card.service.ts, backend/src/modules/cards/services/delete.card.service.ts, backend/src/modules/cards/services/get.card.service.ts, frontend/src/components/Board/AddCardOrComment.tsx, frontend/src/components/Board/Card/CardBoard.tsx, frontend/src/components/Board/Card/CardFooter.tsx, frontend/src/components/Board/Card/CardItem/CardItem.tsx, frontend/src/components/Board/Card/CardItem/CardItemList.tsx, frontend/src/components/Board/Column/CardsList.tsx, frontend/src/components/Board/Column/Column.tsx, frontend/src/components/Board/Comment/Comment.tsx, frontend/src/components/Board/Comment/Comments.tsx, frontend/src/pages/boards/[boardId].tsx, frontend/src/types/card/card.ts, frontend/src/types/card/cardItem.ts, frontend/src/types/column.ts
Relates to #316 
- Add option to post cards anonymously and
- Fix merge cards
- Fix createdBy info
@dsousa12 @tutods 
This pull request closes #316
=> [FEATURE]: option post cards anonymously

frontend/src/pages/boards/[boardId].tsx, frontend/src/types/board/board.ts
Fixes #338 
- Change the type of createdBy on BoardType config.
This pull request closes #338
=> [FIX]: Only show the board settings for the user that created the board

backend/src/modules/boards/services/get.board.service.ts, frontend/src/pages/boards/[boardId].tsx, frontend/src/types/board/board.ts
Fixes #338 
-populate variable createdBy
-change the type of BoardType.createdBy to 'User'
This pull request closes #338
=> [FIX]: Board Settings (Pipeline Error)

frontend/src/helper/board/transformBoard.tsx, frontend/src/hooks/useCards.tsx, frontend/src/hooks/useComments.tsx, frontend/src/hooks/useVotes.tsx
Relates to #330
People involved:
@joaosantos99 @geomarb 
This pull request closes #330
=> [FEATURE]: Optimistic Updates

frontend/src/helper/board/transformBoard.tsx, frontend/src/hooks/useCards.tsx, frontend/src/hooks/useComments.tsx
Fixes #346
This pull request closes #346
=> [FIX]: frontend pipeline

backend/src/modules/boards/controller/boards.controller.ts, backend/src/modules/boards/interfaces/services/get.board.service.interface.ts, backend/src/modules/boards/services/create.board.service.ts, backend/src/modules/boards/services/get.board.service.ts, backend/src/modules/boards/services/update.board.service.ts, frontend/src/components/Board/Settings/index.tsx, frontend/src/components/CardBoard/CardBody/CardEnd.tsx, frontend/src/pages/boards/[boardId].tsx
Relates to #344 
- Validate on Frontend and Backend if the user match with:
- Is Team Admin or Stakeholder
- Is Responsible (only on sub-boards)
- Is the owner 
- Add listener to when user press the enter key submit the form (on Frontend)
Discussed with @CatiaBarroco-xgeeks and @f-morgado 
This pull request closes #334
=> [FEATURE]: Board Settings Permissions

frontend/src/components/Board/Header/index.tsx
Fixes #361
- Add team user avatars in the top right corner of the board page
This pull request closes #361
=> feat(board-header): add team admins avatars

frontend/src/pages/boards/[boardId].tsx
Fixes #353 
- Fix validation to show/hide the message related with sub-boards merged
This pull request closes #353
=> [BUG]: Main board says no sub-team as merged even though it has

frontend/src/pages/boards/[boardId].tsx
Relates to #352 
Fixes #
- change the name button
This pull request closes #352
=> [BUG]: Sub team "merge into main board" typo 

frontend/src/components/Board/Header/index.tsx, frontend/src/components/CardBoard/CardBody/CardBody.tsx
Fixes #357 
- Change the tooltip content 
This pull request closes #357
=> [FIX]: Tooltip Content

backend/src/modules/boards/services/create.board.service.ts, backend/src/modules/cards/services/delete.card.service.ts, backend/src/modules/votes/interfaces/services/delete.vote.service.interface.ts, backend/src/modules/votes/services/delete.vote.service.ts
Fixes #362
- Remove downvote transactions as the votes aren't sensitive data
- Fix board role when the user is admin of a team
This pull request closes #362
=> [REFACTOR]: Remove Downvote Transaction

backend/src/infrastructure/config/configuration.ts
Relates to #336
- rollback string path
=> fix: string path

backend/package-lock.json, backend/package.json, backend/src/modules/boards/services/get.board.service.ts, backend/src/modules/boards/services/update.board.service.ts
Relates to #348 
Fixes #
- Hide card id if card is anonymous and user is different from who created
@f-morgado @dsousa12 
This pull request closes #348
=> [FEATURE]: Hide id from anonymously cards

frontend/src/components/Board/AlertGoToMainBoard/index.tsx, frontend/src/components/Board/AlertMergeIntoMain/index.tsx, frontend/src/components/Board/DragDropArea/index.tsx
- Run **ESLint** with `--fix` to fix the pipeline errors
- The errors are related with new settings on **ESLint**.
=> [FIX]: Pipeline errors after merge

backend/src/modules/cards/controller/cards.controller.ts, frontend/src/components/Board/Card/CardBoard.tsx, frontend/src/components/Board/Card/CardItem/CardItem.tsx
Relates to #395 
- See the text exactly as the user posted it
@dsousa12 
This pull request closes #395
=> [BUG]: TextArea improvements

backend/src/modules/azure/controller/azure.controller.ts, frontend/src/pages/api/auth/[...nextauth].tsx
Fixes #404
- Remove **Local Guard** from Azure Authentication endpoint;
- Remove duplicated `@Post` decorator
People who discussed this issue previously
@f-morgado  @CatiaBarroco-xgeeks 
This pull request closes #404
=> [FIX]: Azure Authentication

frontend/src/components/Board/Card/PopoverSettings.tsx
Fixes #412
- Cap the ability to click multiple times on the unmerge button
This pull request closes #412
=> [BUG] Unmerging cards crashes the website

backend/src/modules/votes/services/create.vote.service.ts, frontend/src/components/Board/Card/CardFooter.tsx
Relates to #409
- backend protection when user adds votes
@f-morgado 
This pull request closes #409
=> [FEATURE]: User vote count limit on a specific board verification 

backend/src/modules/votes/services/create.vote.service.ts, backend/src/modules/votes/services/delete.vote.service.ts
Relates to #425
- in this way the user can't add  or delete votes if it's not allowed
@f-morgado 
This pull request closes #425
=> [FEATURE]: backend vote protection

frontend/src/components/CardBoard/CardBody/CardBody.tsx, frontend/src/components/CardBoard/CardBody/CardEnd.tsx, frontend/src/components/CardBoard/CardBody/CardTitle.tsx, frontend/src/components/CardBoard/CardIcon.tsx
Relates to #443
- changing admin and stakeholder board permissions
This pull request closes #443
=> [BUG]: stakeholder and admin board permissions 

frontend/src/api/boardService.tsx, frontend/src/hooks/useComments.tsx
Fixes #445 
- the user can remove and edit comments on cardgroup
@joaosantos99 @f-morgado 
This pull request closes #445
=> [BUG] Edit/remove comments from merged card

backend/src/modules/boards/services/update.board.service.ts
Relates to #
Fixes #456 
-the board settings update correctly
@dsousa12 
This pull request closes #456
=> [BUG]: BoardSettings response failed 

backend/src/modules/boards/services/get.board.service.ts, backend/src/modules/boards/services/update.board.service.ts, backend/src/modules/comments/applications/create.comment.application.ts, backend/src/modules/comments/controller/comments.controller.ts, backend/src/modules/comments/dto/comment.dto.ts, backend/src/modules/comments/dto/create.comment.dto.ts, backend/src/modules/comments/interfaces/applications/create.comment.application.interface.ts, backend/src/modules/comments/interfaces/services/create.comment.service.interface.ts, backend/src/modules/comments/schemas/comment.schema.ts, backend/src/modules/comments/services/create.comment.service.ts, frontend/src/components/Board/AddCardOrComment.tsx, frontend/src/components/Board/Comment/Comment.tsx, frontend/src/components/Primitives/Checkbox.tsx, frontend/src/types/comment/addComment.dto.ts, frontend/src/types/comment/comment.ts, frontend/src/types/comment/updateComment.dto.ts
Relates to #455
- Add comment anonymously to a cardGroup/cardItem
- UI doesn't show "hidden" names when comment is anonymous (same approach that was done to the cards)
@CatiaBarroco-xgeeks 
This pull request closes #455
=>  [FEATURE]: Comment anonymously 

backend/src/modules/boards/services/get.board.service.ts, backend/src/modules/boards/services/update.board.service.ts, backend/src/modules/comments/applications/create.comment.application.ts, backend/src/modules/comments/controller/comments.controller.ts, backend/src/modules/comments/dto/comment.dto.ts, backend/src/modules/comments/dto/create.comment.dto.ts, backend/src/modules/comments/interfaces/applications/create.comment.application.interface.ts, backend/src/modules/comments/interfaces/services/create.comment.service.interface.ts, backend/src/modules/comments/schemas/comment.schema.ts, backend/src/modules/comments/services/create.comment.service.ts, frontend/src/components/Board/AddCardOrComment.tsx, frontend/src/components/Board/Comment/Comment.tsx, frontend/src/components/Primitives/Checkbox.tsx, frontend/src/helper/board/transformBoard.tsx, frontend/src/types/comment/addComment.dto.ts, frontend/src/types/comment/comment.ts, frontend/src/types/comment/updateComment.dto.ts
Relates to #459
- Type error on comment
This pull request closes #459
=> [BUG] Anonymous card name revealed 

frontend/src/components/CreateBoard/SubTeamsTab/TeamSubTeamsConfigurations.tsx
Fixes #472 
- Stakeholder names divided, a board with more than 1 stakeholder separated with commas
-
This pull request closes #472
=> [BUG] Stakeholder names incorrect

backend/src/modules/boards/services/update.board.service.ts, backend/src/modules/cards/services/unmerge.card.service.ts, frontend/src/components/Board/Card/CardBoard.tsx, frontend/src/components/Board/Card/CardFooter.tsx, frontend/src/components/Board/Card/CardItem/CardItem.tsx, frontend/src/components/Board/Card/CardItem/CardItemList.tsx
Fixes #460 
Fixes #459 
- After the subBoard is merged to the main board, users can merge and unmerge the cards without losing the existing properties of the cardFooter
@miguel-felix1 
This pull request closes #460 
This pull request closes #459
=> [BUG] Merging cards from a sub-team on the main board

frontend/src/components/Board/Card/CardFooter.tsx
Relates to #480
[BUG] Voting/Comment icons misaligned
- Align the icons to the right position
This pull request closes #480
=> [BUG] Voting/Comment icons misaligned

database/rs-init.sh
Fixes #496 
- Add the correct configuration of the file rs-init.sh
@joaosantos99 
This pull request closes #496
=> [FIX]: Add correct config

backend/src/modules/cards/services/unmerge.card.service.ts
Fixes #477
- Forcing the card anonymous property to maintain is original state
This pull request closes #477
=> [FIX] Anonymous card identity

frontend/src/components/Board/Column/Column.tsx
Fixes #476
- Get the count number from a single source of truth
This pull request closes #476
=> [FIX] shorting merged cards

backend/src/libs/dto/param/socket.param.ts, backend/src/modules/boards/controller/boards.controller.ts, backend/src/modules/socket/gateway/socket.gateway.ts, backend/src/modules/socket/interfaces/joinPayloadBoards.interface.ts, frontend/src/api/boardService.tsx, frontend/src/components/Board/AlertMergeIntoMain/index.tsx, frontend/src/hooks/useCards.tsx, frontend/src/pages/boards/[boardId].tsx
Relates to #465
- When the responsible merges the board to main Board all the users will receive a socket to be instantly updated
@f-morgado 
This pull request closes #465
=> [BUG] Adding cards to closed sub-board

frontend/src/components/Board/Column/Column.tsx, frontend/src/pages/boards/[boardId].tsx
- import order
@CatiaBarroco-xgeeks
=> [FIX]:  eslint issues import order

backend/src/libs/dto/param/socket.param.ts, backend/src/modules/boards/controller/boards.controller.ts, backend/src/modules/socket/gateway/socket.gateway.ts, backend/src/modules/socket/interfaces/joinPayloadBoards.interface.ts, frontend/src/api/boardService.tsx, frontend/src/components/Board/AlertMergeIntoMain/index.tsx, frontend/src/components/Board/Column/Column.tsx, frontend/src/components/icons/Sprite.tsx, frontend/src/hooks/useCards.tsx, frontend/src/pages/boards/[boardId].tsx
Relates to #509 
- fix eslint error
@dsousa12
=> [FIX]: adding cards to closed sub boad eslint issues

frontend/src/components/icons/Sprite.tsx
Fix errors on Sprite by ESLint rules
Relates to #510
=> fix(NI): ESLint errors on Sprite

frontend/src/components/Teams/MyTeams/partials/CardTeam/CardBody.tsx
Relates to #501 
- Fix the layout of the team card when the user isn't an admin or super admin
This pull request closes #501
=> [FIX]: fix card team layout

backend/src/libs/dto/param/team.param.optional.ts, backend/src/modules/boards/controller/boards.controller.ts, backend/src/modules/socket/gateway/socket.gateway.ts, backend/src/modules/socket/interfaces/joinPayloadBoards.interface.ts, frontend/src/api/boardService.tsx, frontend/src/components/Boards/MyBoards/index.tsx, frontend/src/components/CardBoard/CardBody/CardBody.tsx, frontend/src/components/CardBoard/CardBody/CardEnd.tsx, frontend/src/components/CardBoard/DeleteBoard.tsx, frontend/src/components/Dashboard/RecentRetros/index.tsx, frontend/src/hooks/useSocketBoardIO.ts, frontend/src/pages/board-deleted.tsx, frontend/src/pages/boards/[boardId].tsx, frontend/src/types/board/useBoard.ts, frontend/src/utils/fetchData.tsx
Relates to #464 
Relates to #478
- if someone deletes a certain board the other users will have an update of the list of boards
- or if the other users are inside the board they will be redirected to a page warning with the information that the board has been deleted
@f-morgado 
This pull request closes #464 
This pull request closes #478
=> [BUG] Accessing a deleted board

frontend/src/components/Primitives/Input.tsx, frontend/src/components/Teams/CreateTeam/ListCardsMembers/index.tsx, frontend/src/components/Teams/CreateTeam/ListMembers/index.tsx, frontend/src/components/Teams/CreateTeam/ListMembers/styles.tsx, frontend/src/pages/teams/new.tsx, frontend/src/schema/schemaAddMemberForm.ts
Relates to #521 
-The layout of the drawer that which is opened by the button 'add new member' is added.
This pull request closes #521
=> [FEATURE]: Drawer with members

backend/src/modules/users/applications/get.user.application.ts, backend/src/modules/users/controller/users.controller.ts, backend/src/modules/users/interfaces/applications/get.user.application.interface.ts, backend/src/modules/users/interfaces/services/get.user.service.interface.ts, backend/src/modules/users/services/get.user.service.ts, backend/src/modules/users/users.module.ts
Relates to #524 
-Users controller created, which allows the definition of the getAllUsers() endpoint to retrieve all users
This pull request closes #524
=> [FEATURE]: add users controller

README.md
Add usage icon and `/boards` url
=> [REFACTOR]: update readme

backend/src/libs/dto/param/user.params.ts, backend/src/modules/teams/controller/team.controller.ts, frontend/src/api/teamService.tsx, frontend/src/components/Teams/CreateTeam/ListMembers/index.tsx, frontend/src/components/Teams/MyTeams/index.tsx, frontend/src/pages/teams/index.tsx
Relates to #541 
- On the page "Teams", the endpoint that now is being used is `getTeamsOfUser()` instead `getAllTeams()` 
- Add endpoint to teams controller
This pull request closes #541
=> [FEATURE]: endoint to get the teams of a user

frontend/src/components/Boards/MyBoards/styles.tsx, frontend/src/components/Dashboard/RecentRetros/partials/ListOfCards/index.tsx
Fixes #551 
- Extra bottom space removed
This pull request closes #551
=> [FIX]:  Board list bottom cut off

backend/src/modules/queue/queue.module.ts, backend/src/modules/schedules/services/create.schedules.service.ts, frontend/src/components/CardBoard/CardAvatars.tsx, frontend/src/components/CardBoard/CardBody/CardBody.tsx, frontend/src/components/CreateBoard/SubTeamsTab/TeamSubTeamsConfigurations.tsx, frontend/src/hooks/useBoard.tsx, frontend/src/hooks/useCreateBoard.tsx
Fixes #553
- Fix cron job deletion failure
- Remove the last comma when showing the stakeholders on the create new board page
This pull request closes #553
=> [FIX]: stakeholders, delete cron job

frontend/src/api/boardService.tsx, frontend/src/components/Board/Card/CardFooter.tsx, frontend/src/components/Board/DragDropArea/index.tsx, frontend/src/helper/board/transformBoard.tsx, frontend/src/hooks/useVotes.tsx, frontend/src/pages/boards/new.tsx
Fixes #552
- Fix unmerge optimistic update
- Fix the cancel button, should return to the previous page - not only to boards list
- Add remaining votes toast info when the board has a vote limit
This pull request closes #552
=> [Fix]: unmerge cards and remaining votes

backend/src/modules/teams/applications/create.team.application.ts, backend/src/modules/teams/controller/team.controller.ts, backend/src/modules/teams/dto/team.user.dto.ts, backend/src/modules/teams/interfaces/applications/create.team.application.interface.ts, backend/src/modules/teams/interfaces/services/create.team.service.interface.ts, backend/src/modules/teams/schemas/team.user.schema.ts, backend/src/modules/teams/services/create.team.service.ts, backend/src/modules/teams/services/get.team.service.ts, backend/src/modules/users/services/create.user.service.ts, backend/src/modules/users/users.module.ts, frontend/src/components/Teams/MyTeams/index.tsx, frontend/src/components/Teams/MyTeams/partials/CardTeam/CardBody.tsx, frontend/src/components/Teams/MyTeams/partials/EmptyTeams/index.tsx, frontend/src/components/auth/SignUp/SignUpForm.tsx, frontend/src/pages/teams/index.tsx
Fixes #569 
- Remove logic to  add user to team from register new user
- Add isNewbie attribute to TeamUserDto
- Temporary fix on the sign up form
- Fix countTeams of user
This pull request closes #569
=> [REFACTOR]: change create teams logic

backend/src/modules/teams/dto/team.user.dto.ts, frontend/src/api/teamService.tsx, frontend/src/components/Teams/CreateTeam/ListMembers/index.tsx, frontend/src/components/Teams/CreateTeam/index.tsx, frontend/src/hooks/useTeam.tsx, frontend/src/pages/teams/index.tsx, frontend/src/pages/teams/new.tsx, frontend/src/types/team/team.ts, frontend/src/types/team/team.user.ts, frontend/src/types/team/useTeam.ts
Relates to #571 
- Change attribute name from isNewbie to isNewJoiner on the backend
- UseTeam with all the queries and mutations created
- Add function to save the new team
This pull request closes #571
=> [FEATURE]: submit created team

docker-compose.dev.yaml
Fixes #585 
- Add redis configuration to docker-compose.dev
This pull request closes #585
=> [BUG]: fix docker-compose.dev

backend/.env.example, backend/src/modules/boards/services/update.board.service.ts, backend/src/modules/schedules/services/create.schedules.service.ts, frontend/.env.example, frontend/src/components/auth/LoginForm/index.tsx, frontend/src/hooks/useCards.tsx
Fixes #578
- Fix unauthorised login error
- Optimistic create card with a user
- Change responsible slack message only when the responsible was changed
This pull request closes #578
=> fix(issues): unauthorised login error, create card with user, change responsible slack message

.all-contributorsrc
This pull request fixes the malformed all-contributors file
=> [FIX]: Update .all-contributorsrc file

backend/src/main.ts
- Added API collection download link to Swagger
=> feat: add download link to swagger

backend/src/modules/auth/services/validate-user.auth.service.spec.ts, backend/src/modules/teams/interfaces/services/get.team.service.interface.ts, backend/src/modules/teams/interfaces/users-with-teams.interface.ts, backend/src/modules/teams/services/get.team.service.ts, backend/src/modules/teams/teams.module.ts, backend/src/modules/users/applications/get.user.application.ts, backend/src/modules/users/controller/users.controller.ts, backend/src/modules/users/interfaces/applications/get.user.application.interface.ts, backend/src/modules/users/interfaces/services/get.user.service.interface.ts, backend/src/modules/users/interfaces/type-user-with-teams.ts, backend/src/modules/users/services/get.user.service.ts, backend/src/modules/users/swagger/users-with-teams.swagger.ts
Relates to #598
This pull request closes #598
=> feat(teams): added endpoint to get users with corresponding teams

frontend/src/utils/fetchData.tsx
Fixes #639 
- Remove the try catch on fetch data so the react query can receive the error
This pull request closes #639
=> fix: fetchData method return

frontend/package-lock.json, frontend/package.json, frontend/src/components/Teams/TeamsList/partials/CardTeam/CardBody.tsx, frontend/src/pages/api/auth/[...nextauth].tsx, frontend/src/pages/boards/[boardId].tsx, frontend/src/pages/boards/index.tsx, frontend/src/pages/boards/new.tsx, frontend/src/pages/dashboard/index.tsx, frontend/src/types/next-auth.d.ts, frontend/src/types/token.ts, frontend/src/types/user/user.ts, frontend/src/utils/fetchData.tsx
Fixes #646
- Update nextauth package
- Solve update package issues
- Add context on the server side request for teams of the user
- Refactor nextauth types
This pull request closes #646
=> fix: unauthorised error on dashboard

frontend/src/components/Teams/CreateTeam/CardMember/index.tsx, frontend/src/components/Teams/Team/CardEnd/index.tsx
Relates to #624 
- Super Admin has permission to edit and remove teams
This pull request closes #624
=> feat: super admin allowed to change teams

backend/src/libs/guards/teamRoles.guard.ts, backend/src/modules/teams/controller/team.controller.ts, frontend/src/components/Teams/CreateTeam/CardMember/index.tsx, frontend/src/components/Teams/Team/CardEnd/index.tsx, frontend/src/components/Teams/Team/ListCardMembers/index.tsx, frontend/src/components/Teams/TeamsList/partials/CardTeam/BoardsInfo.tsx, frontend/src/components/Teams/TeamsList/partials/CardTeam/CardBody.tsx
Relates to #638 
- Allow stakeholders edit and remove teams
This pull request closes #638
=> feat: add stakeholder permissions team

backend/src/modules/boards/boards.module.ts, backend/src/modules/boards/controller/boards.controller.ts, backend/src/modules/boards/interfaces/services/delete.board.service.interface.ts, backend/src/modules/boards/interfaces/services/get.board.service.interface.ts, backend/src/modules/boards/services/delete.board.service.ts, backend/src/modules/boards/services/get.board.service.ts, backend/src/modules/teams/interfaces/services/delete.team.service.interface.ts, backend/src/modules/teams/services/delete.team.service.ts, backend/src/modules/teams/teams.module.ts
Fixes #651 
- Delete boards of deleted team.
This pull request closes #651
=> fix: delete team removes associated boards

frontend/src/components/Board/Card/CardFooter.tsx, frontend/src/helper/board/transformBoard.tsx, frontend/src/hooks/useVotes.tsx
- Handle the success status of the vote request enabling the buttons to vote
=> refactor: handle disable vote buttons

backend/src/libs/repositories/interfaces/base.repository.interface.ts, backend/src/modules/auth/services/validate-user.auth.service.ts, backend/src/modules/auth/strategy/refresh.strategy.ts, backend/src/modules/users/repository/user.repository.ts, backend/src/modules/users/services/update.user.service.ts, frontend/src/pages/api/auth/[...nextauth].tsx
Fixes #694 
- Fix the nextAuth refresh token request
- Save the current refresh token
This pull request closes #694
=> fix: request new access token with refresh token

frontend/src/components/Board/Card/CardBoard.tsx, frontend/src/components/Board/Card/CardItem/CardItem.tsx, frontend/src/components/Board/Comment/Comment.tsx
Fixes #656 
- Use pre-line
- Add missed break-word
=> fix: large cards

frontend/src/components/Board/Card/PopoverSettings.tsx, frontend/src/helper/board/transformBoard.tsx
Fixes #699
- Fix the new position to insert the removed card from the group
This pull request closes #699
=> fix: unmerge cards positions

frontend/src/api/userService.tsx, frontend/src/components/Users/UsersList/partials/CardUser/EditUser.tsx, frontend/src/components/Users/UsersList/partials/ListOfCards/index.tsx
-  filter user by typing into the search user box
-  debounce mechanism of 100ms
- checks for firstname, lastname and email
This pull request closes #601
=> feat: frontend done for search user

frontend/package-lock.json, frontend/package.json, frontend/src/components/Board/DragDropArea/index.tsx, frontend/src/helper/board/transformBoard.tsx, frontend/src/types/board/mergeCard.dto.ts
Fixes #708
- fix the transform board
This pull request closes #708
=> fix: merge card position

backend/src/modules/boards/services/create.board.service.ts, frontend/src/hooks/useCreateBoard.tsx
Fixes #726 
- Fix division of users by the sub-boards 
This pull request closes #726
=> fix: fix split of teams by sub-board

frontend/src/components/Teams/CreateTeam/ListCardsMembers/index.tsx, frontend/src/components/Teams/Team/ListCardMembers/index.tsx, frontend/src/pages/teams/index.tsx
Relates to #687
Fixes #752 
- Fix "Add/remove members" button to show dialog.
- Super Admin sees all existing teams on teams page.
This pull request closes #687 #752
=> feat: superadmin gets all the teams

frontend/src/api/teamService.tsx, frontend/src/components/Teams/CreateTeam/CardMember/RoleSettings.tsx, frontend/src/components/Users/UserEdit/partials/TeamsDialog/index.tsx, frontend/src/components/Users/UsersList/partials/CardUser/CardBody.tsx, frontend/src/components/Users/UsersList/partials/CardUser/EditUser.tsx, frontend/src/hooks/useTeam.tsx, frontend/src/types/team/team.ts, frontend/src/types/team/useTeam.ts, frontend/src/utils/routes.ts
- fetch teams user is not member
- check and uncheck teams
- "Add" updates the DB, adding the selected teams to the user. Then it closes the dialog
This pull request closes #749 and #750
=> feat: fetch teams, add teams to user, filter by search

frontend/src/components/Primitives/Checkbox.tsx, frontend/src/components/Teams/CreateTeam/CardMember/styles.tsx, frontend/src/components/Teams/CreateTeam/ListMembers/index.tsx
Fixes #731
- Add word break
This pull request closes #731
=> fix: large names

frontend/src/components/Users/UserEdit/partials/TeamsDialog/index.tsx
#763 
Fixes #763
- Change the logic used on useEffect to get the data. 
- Don't use useRef
@GuiSanto 
This pull request closes #763
=> fix: only makes request when the dialog is opened

backend/src/modules/users/applications/get.user.application.ts, backend/src/modules/users/controller/users.controller.ts, backend/src/modules/users/interfaces/applications/get.user.application.interface.ts, frontend/jest.setup.js, frontend/src/__tests__/index.test.tsx, frontend/src/api/userService.tsx, frontend/src/components/Users/UserEdit/partials/TeamsDialog/index.tsx, frontend/src/components/Users/UserEdit/partials/UserHeader/index.tsx, frontend/src/components/Users/UsersList/partials/CardUser/CardBody.tsx, frontend/src/components/Users/UsersList/partials/CardUser/EditUser.tsx, frontend/src/hooks/useTeam.tsx, frontend/src/hooks/useUser.tsx, frontend/src/hooks/useUserUtils.tsx, frontend/src/pages/users/[userId].tsx, frontend/src/types/user/user.ts, frontend/src/utils/routes.ts
#770 
Fixes #770 
With params:
No params:
- Get user info by making a database request instead of passing the info by params.
@GuiSanto 
This pull request closes #770
=> fix: get user info

backend/src/libs/enum/board.roles.ts, backend/src/libs/utils/generateBoardData.ts, backend/src/modules/boards/dto/board.dto.ts, backend/src/modules/boards/schemas/board.schema.ts, backend/src/modules/boards/schemas/board.user.schema.ts, backend/src/modules/boards/services/create.board.service.ts, backend/src/modules/boards/services/update.board.service.ts, backend/src/modules/votes/services/create.vote.service.ts, backend/src/modules/votes/services/delete.vote.service.ts, frontend/src/components/Board/AlertGoToMainBoard/index.tsx, frontend/src/components/Board/Header/index.tsx, frontend/src/components/Boards/MyBoards/ListBoardMembers/index.tsx, frontend/src/components/Boards/MyBoards/styles.tsx, frontend/src/components/CardBoard/CardAvatars.tsx, frontend/src/components/CardBoard/CardBody/CardBody.tsx, frontend/src/components/Teams/CreateTeam/ListCardsMembers/index.tsx, frontend/src/components/Teams/Team/ListCardMembers/index.tsx, frontend/src/hooks/useCreateBoard.tsx, frontend/src/pages/boards/[boardId].tsx, frontend/src/pages/boards/newRegularBoard.tsx, frontend/src/pages/boards/newSplitBoard.tsx, frontend/src/store/createBoard/atoms/create-board.atom.tsx, frontend/src/types/board/board.ts, frontend/src/utils/enums/board.user.roles.ts
Fixes #777
- Remove stakeholder role from board user model. The responsible should be a user with privileges in a board
- Fix layout issue in a sub-board
- The responsible of each sub-board can now change the main board settings
This pull request closes #777
=> refactor: board issues 

backend/src/libs/exceptions/messages.ts, backend/src/modules/boards/services/create.board.service.ts, backend/src/modules/cards/services/delete.card.service.ts, backend/src/modules/votes/applications/create.vote.application.ts, backend/src/modules/votes/applications/delete.vote.application.ts, backend/src/modules/votes/controller/votes.controller.ts, backend/src/modules/votes/interfaces/applications/create.vote.application.interface.ts, backend/src/modules/votes/interfaces/applications/delete.vote.application.interface.ts, backend/src/modules/votes/interfaces/services/create.vote.service.interface.ts, backend/src/modules/votes/interfaces/services/delete.vote.service.interface.ts, backend/src/modules/votes/services/create.vote.service.ts, backend/src/modules/votes/services/delete.vote.service.ts, frontend/src/components/Board/Card/CardFooter.tsx, frontend/src/hooks/useVotes.tsx
Relates to #778
- Add debounce to add or remove votes
- The votes are now counted and after 300ms the request is sent with the count value
- The backend now uses the count that is sent from the frontend to decrease or increase votes
This pull request closes #778
=> fix: votes

frontend/src/components/Dashboard/RecentRetros/index.tsx, frontend/src/pages/boards/newRegularBoard.tsx
Relates to #790 
- Fix dashboard error
- Add quick board
This pull request closes #790
=> feat: add empty regular board

frontend/src/components/Teams/Team/ListCardMembers/index.tsx, frontend/src/pages/boards/newRegularBoard.tsx
Fixes #798 
- Fix error when creating a regular board with a team
- Fix show btn add/remover members on team page
This pull request closes #798
=> fix: fix add responsibles field to boardData

backend/src/modules/boards/services/create.board.service.ts, backend/src/modules/boards/services/update.board.service.ts, backend/src/modules/votes/services/create.vote.service.ts, backend/src/modules/votes/services/delete.vote.service.ts, frontend/src/components/Board/Card/CardFooter.tsx, frontend/src/hooks/useVotes.tsx
Relates to #778 
- Fix session
=> fix: votes and responsibles

backend/src/modules/communication/adapters/slack-communication-gate.adapter.ts, backend/src/modules/communication/producers/slack-communication.producer.ts, frontend/src/components/Board/Settings/index.tsx, frontend/src/components/Board/Settings/styles.tsx, frontend/src/components/Boards/MyBoards/ListBoards/index.tsx, frontend/src/components/Boards/MyBoards/styles.tsx, frontend/src/components/Primitives/Button.tsx, frontend/src/components/Primitives/Dialog/DialogFooter.tsx, frontend/src/components/Teams/CreateTeam/CardMember/index.tsx, frontend/src/components/Teams/TeamsList/partials/CardTeam/CardBody.tsx, frontend/src/components/Teams/TeamsList/partials/CardTeam/CardTitle.tsx, frontend/src/components/Users/UsersList/partials/CardUser/CardBody.tsx, frontend/src/components/Users/UsersList/partials/CardUser/EditUser.tsx, frontend/src/components/Users/UsersList/partials/ListOfCards/index.tsx, frontend/src/hooks/useBoard.tsx, frontend/src/hooks/useCards.tsx, frontend/src/hooks/useComments.tsx, frontend/src/pages/boards/newSplitBoard.tsx, frontend/src/pages/teams/index.tsx, frontend/src/styles/stitches/partials/colors/primary.colors.ts
Fixes #765 , #775, #801
- The main board now has all the supposed responsibilities 
- Board settings below dialog buttons 
- Team creator can now change his newJoiner status or his role
- Fix some card body issues
This pull request closes #765 and closes #775 and closes #801
=> fix: some bugs

frontend/src/components/CreateBoard/SplitBoard/SubTeamsTab/BoxContainer/index.tsx, frontend/src/components/CreateBoard/SplitBoard/SubTeamsTab/UsersBox/index.tsx
Fixes #812
- Change padding and height of box 
@GuiSanto 
This pull request closes #812 
> Can you post a screenshot about this change? Like the result?
=> fix: padding of stakeholders box when creating board

backend/src/libs/dto/param/pagination.params.ts, backend/src/modules/boards/applications/get.board.application.ts, backend/src/modules/boards/controller/boards.controller.ts, backend/src/modules/boards/interfaces/applications/get.board.application.interface.ts, backend/src/modules/boards/interfaces/findQuery.ts, backend/src/modules/boards/interfaces/services/get.board.service.interface.ts, backend/src/modules/boards/services/get.board.service.ts
Relates to #791 
- Get Personal Boards from backend with pagination.
=> feat: personal filter boads page endpoint

backend/src/modules/boards/services/create.board.service.ts, frontend/src/components/Boards/MyBoards/index.tsx, frontend/src/components/Dashboard/RecentRetros/index.tsx
Fixes #819
- In a board creation when the mainboard has the slack option enabled, the sub-boards should copy that value
This pull request closes #819
=> fix: add slack enable in the sub boards

backend/src/modules/schedules/services/create.schedules.service.ts, frontend/.eslintrc.json, frontend/src/components/Board/Card/CardBoard.tsx, frontend/src/components/Board/Card/CardItem/CardItem.tsx, frontend/src/components/Board/Settings/index.tsx, frontend/src/components/Boards/MyBoards/index.tsx, frontend/src/components/Teams/CreateTeam/index.tsx, frontend/src/components/Teams/Team/ListCardMembers/styles.tsx, frontend/src/components/Users/UsersList/partials/ListOfCards/index.tsx, frontend/src/pages/boards/[boardId].tsx, frontend/src/schema/schemaRegisterForm.ts
Fixes #816
Fixes #815 
Fixes #813 
Fixes #810 
Fixes #817
- Protect a board from a user that isn't participating or doesn't have privileges 
- Disable create team after first successful submit 
- Remove alphanumeric rule in register fields 
- Avoid unmerge when the cards are hidden
- Fix board settings switches
This pull request closes #816 and closes #815 and closes #813 and closes #810 and closes #817
=> fix: board access and other fixes

frontend/src/components/Boards/TeamHeader.tsx, frontend/src/components/Teams/TeamsList/partials/CardTeam/CardTitle.tsx, frontend/src/components/Users/UsersList/partials/CardUser/CardBody.tsx, frontend/src/components/Users/UsersList/partials/CardUser/CardTitle.tsx
- Fix names user, teams and boards overflow
This pull request closes #
=> fix: bug names

backend/src/modules/boards/services/create.board.service.ts, frontend/src/hooks/useCreateBoard.tsx
Fixes #833
- Distribute board users evenly for each sub board.
This pull request closes #833
=> fix: users distributed evenly per sub board

backend/src/libs/repositories/interfaces/base.repository.interface.ts, backend/src/libs/repositories/mongo/mongo-generic.repository.ts, backend/src/modules/teams/services/update.team.service.ts, backend/src/modules/users/services/get.user.service.ts, backend/src/modules/users/utils/sortings.ts, frontend/src/components/CreateBoard/RegularBoard/ParticipantsTab/ListParticipants/index.tsx, frontend/src/components/Teams/CreateTeam/ListMembers/index.tsx, frontend/src/components/Teams/CreateTeam/ListMembersDialog/index.tsx
Relates to #838 
Fixes #838 
- The ListMembersDialog is now an independent component, it doesn't matter how he gets the users.
- The component will sort the list it receives by:
- Alphabetically
- By Checked
- Team Admin always on the first position 
- getAllUsers from Backend will return an ordered list of users.
This pull request closes #838
=> fix: team members list ordering

backend/src/modules/teams/services/get.team.service.ts, backend/src/modules/users/services/get.user.service.ts, frontend/src/api/userService.tsx, frontend/src/components/Users/UsersList/partials/ListOfCards/index.tsx
Relates to #850 
Fixes #850 
- When fetching the page data from the backend, it also sends the total user amount
- In the frontend, it displays the total registered users.
- Fetching new users while scrolling doesn't change this number.
This pull request closes #850
=> fix: registered users amount

frontend/src/components/Dashboard/Tiles/index.tsx, frontend/src/components/Dashboard/Tiles/styles.tsx, frontend/src/pages/boards/newRegularBoard.tsx
Fixes #865 
- Add arrows and links o tiles on Dashboard
- Quick create option is first
This pull request closes #865
=> fix: dashboard links

frontend/src/components/Board/Column/Column.tsx, frontend/src/components/Board/Column/partials/ColorSquare/index.tsx, frontend/src/components/Board/Column/partials/OptionsMenu/index.tsx, frontend/src/components/Board/Column/partials/OptionsMenu/styles.tsx, frontend/src/components/Board/Column/partials/SwitchDefaultText/index.tsx, frontend/src/components/Board/DragDropArea/index.tsx, frontend/src/components/Board/RegularBoard/index.tsx, frontend/src/components/Primitives/Switch.tsx, frontend/src/pages/boards/[boardId].tsx
Relates to #875 
- Add popover with options (just the design)
- Only users with adminRoles can access this options
This pull request closes #875
=> feat: column operation popover

frontend/src/components/CreateBoard/RegularBoard/ParticipantsTab/RadioGroupParticipants/index.tsx, frontend/src/components/CreateBoard/RegularBoard/SettingsTabs/index.tsx, frontend/src/components/CreateBoard/Select/index.tsx, frontend/src/components/CreateBoard/SplitBoard/SettingsTabs.tsx
Relates to #887 
Fixes #887 
- New SPLIT board main content distances
- New regular board main content distances
- New regular board radio boxes cursor pointer
This pull request closes #887
=> fix: bug new board design fixes

frontend/src/components/Boards/MyBoards/ListBoards/index.tsx, frontend/src/components/Dashboard/RecentRetros/partials/ListOfCards/index.tsx
Relates to #894
Fixes #894
- Show last updated date on non team admins
- Enlarge gap between boards (according to figma design)
This pull request closes #894
=> fix: last updated dates not showing in boards list page

frontend/src/components/CardBoard/CardBody/CardBody.tsx
Relates to #904 
Fixes #904 
- As a Super-Admin I have access to all boards / sub-boards
This pull request closes #904
=> fix: super-admin access

frontend/src/hooks/useCreateBoard.tsx
Relates to #918  
Fixes #918 
- Fixed Decimal Number in the Quick Edit Sub-Teams Modal
- Changed the .toFixed(2) that introduced a decimal point
This pull request closes #918
=> fix: removed decimal part

frontend/src/components/CreateBoard/SplitBoard/SubTeamsTab/MainBoardCard.tsx, frontend/src/components/Primitives/Checkbox.tsx, frontend/src/components/Teams/CreateTeam/index.tsx, frontend/src/hooks/useCreateBoard.tsx, frontend/src/pages/boards/newRegularBoard.tsx, frontend/src/pages/boards/newSplitBoard.tsx
Fixes #911 
- Store checkbox state using react hook form
- Fix form submission on board and team creation
=> fix: enableSlack with hook form and fix form submissions

frontend/src/stories/Box.stories.tsx, frontend/src/stories/Button.stories.tsx, frontend/src/stories/Flex.stories.tsx, frontend/src/stories/types/PrimitiveTypes.tsx, frontend/src/stories/utils/index.tsx
Relates to #936 
Fixes #936
- Added Flex Story
- Added File with Primitive Types
- Added Capitalize utility function
This pull request closes #936
=> feat: flex story

backend/src/modules/boards/controller/boards.controller.ts, backend/src/modules/communication/adapters/slack-communication-gate.adapter.ts, backend/src/modules/socket/gateway/socket.gateway.ts
- Add missing destination room when sending the board updates with socket
=> fix: missing socket send room

backend/src/modules/azure/azure.module.ts, backend/src/modules/azure/services/auth.azure.service.ts, backend/src/modules/communication/applications/slack-add-user-channel.application.ts, backend/src/modules/communication/communication.module.ts, backend/src/modules/communication/communication.providers.ts, backend/src/modules/communication/consumers/slack-add-user-channel.consummer.ts, backend/src/modules/communication/dto/types.ts, backend/src/modules/communication/interfaces/communication.application.interface copy.ts, backend/src/modules/communication/interfaces/slack-communication.service.interface.ts, backend/src/modules/communication/interfaces/types.ts, backend/src/modules/communication/producers/slack-add-user-channel.producer.ts, backend/src/modules/communication/services/slack-communication.service.ts, backend/src/modules/communication/services/slack-disabled-communication.service.ts, backend/src/modules/teams/services/get.team.service.ts, frontend/src/components/Board/DragDropArea/index.tsx, frontend/src/components/Boards/MyBoards/ListBoardMembers/FilterBoardMembers/index.tsx, frontend/src/components/Boards/MyBoards/ListBoards/index.tsx, frontend/src/components/CardBoard/CardBody/CardBody.tsx, frontend/src/components/Primitives/Avatar.tsx, frontend/src/components/Teams/CreateTeam/ListMembers/index.tsx, frontend/src/components/Teams/Team/ListCardMembers/index.tsx, frontend/src/components/Teams/TeamsList/partials/CardTeam/CardBody.tsx, frontend/src/pages/boards/[boardId].tsx, frontend/src/pages/teams/[teamId].tsx
Relates to #946 
- The registered user with azure sso is added into the slack main channel
- A new queue was added to handle the invitations
This pull request closes #946
=> feat: add user to main channel; fix deleted user issues

backend/src/libs/constants/team.ts, backend/src/modules/teams/entities/teams.schema.ts, backend/src/modules/teams/services/create.team.service.ts, frontend/src/components/Teams/CreateTeam/ListCardsMembers/index.tsx, frontend/src/components/Teams/CreateTeam/index.tsx, frontend/src/errors/teams/errors.ts, frontend/src/hooks/useTeam.tsx
- Avoiding the duplication of team names
=> refactor: protect team names duplication

backend/src/libs/utils/ordinal-date.ts, backend/src/modules/communication/applications/slack-communication.application.ts, frontend/src/components/Board/Settings/index.tsx, frontend/src/schema/schemaUpdateBoardForm.ts
Fixes #954
- Board settings component now handles if it's a split or regular board
This pull request closes #954
=> fix: settings in a split board

backend/src/modules/boards/services/create.board.service.ts
Relates to #961
Fixes #961
- Fix create regular boards.
This pull request closes #961
=> fix: create regular board working

frontend/src/components/Board/Card/CardFooter.tsx, frontend/src/components/Boards/MyBoards/ListBoardMembers/FilterBoardMembers/index.tsx, frontend/src/components/CreateBoard/SplitBoard/SubTeamsTab/SubCardBoard.tsx, frontend/src/components/Primitives/Avatar.tsx, frontend/src/stories/Avatar.stories.tsx
Relates to #976 
Fixes #976 
- Add the Avatar primitive to Storybook
- Normalize Avatar primitive component throughout the application
This pull request closes #976
=> feat: avatar primitive story

backend/src/modules/azure/services/auth.azure.service.ts, backend/src/modules/boards/services/update.board.service.ts, frontend/src/hooks/useCards.tsx
Fixes #982 
- Fix the error when a responsible from a sub-board tries to update the settings on a main board
This pull request closes #982
=> fix: main board settings

backend/src/modules/boards/services/create.board.service.ts, backend/src/modules/boards/services/update.board.service.ts, frontend/src/helper/board/transformBoard.tsx, frontend/src/utils/verifyIfIsNewJoiner.ts
Fixes #997 
- add 15 days to new joiner period
- fix votes
- fix responsible when updating a board
This pull request closes #997
=> fix: isNewJoiner period and votes

backend/src/modules/teams/applications/get.team.application.ts, backend/src/modules/teams/controller/team.controller.ts, backend/src/modules/teams/interfaces/applications/get.team.application.interface.ts, backend/src/modules/teams/interfaces/services/get.team.service.interface.ts, backend/src/modules/teams/services/get.team.service.ts, frontend/src/components/Boards/MyBoards/index.tsx, frontend/src/hooks/useTeam.tsx, frontend/src/hooks/useTeamUtils.tsx, frontend/src/pages/boards/index.tsx, frontend/src/pages/boards/newRegularBoard.tsx, frontend/src/pages/boards/newSplitBoard.tsx, frontend/src/pages/teams/index.tsx, frontend/src/types/team/useTeam.ts
Relates to #1004 
Fixes #1004 
- Change Frontend Requests so that Non-Super Admins don't have access to All Teams
- [GET /teams] Guard Route to only allow Super Admin Access
This pull request closes #1004
=> fix: teams page has all teams in application

backend/src/libs/dto/colum.deleteCards.dto.ts, backend/src/modules/boards/applications/update.board.application.ts, backend/src/modules/boards/controller/boards.controller.ts, backend/src/modules/boards/dto/column/column.dto.ts, backend/src/modules/boards/dto/column/update-column.dto.ts, backend/src/modules/boards/interfaces/applications/update.board.application.interface.ts, backend/src/modules/boards/interfaces/services/update.board.service.interface.ts, backend/src/modules/boards/schemas/column.schema.ts, backend/src/modules/boards/services/update.board.service.ts
Relates to #958
- Add endpoint to backend that deletes all the cards from a specific column and returns the votes to the users
- ColumnDto schema refactored
=> feat: delete all card from a column

backend/src/modules/boards/interfaces/services/get.board.service.interface.ts, backend/src/modules/boards/services/create.board.service.ts, backend/src/modules/boards/services/get.board.service.ts, backend/src/modules/boards/services/update.board.service.ts, backend/src/modules/boards/utils/populate-board.ts, backend/src/modules/cards/applications/delete.card.application.ts, backend/src/modules/cards/controller/cards.controller.ts, backend/src/modules/cards/interfaces/applications/delete.card.application.interface.ts, backend/src/modules/cards/interfaces/services/delete.card.service.interface.ts, backend/src/modules/cards/services/delete.card.service.ts, backend/src/modules/schedules/services/create.schedules.service.ts, frontend/src/components/Board/Card/CardBoard.tsx, frontend/src/components/Board/Card/CardFooter.tsx, frontend/src/components/Board/Card/CardItem/CardItem.tsx, frontend/src/components/Board/Card/PopoverSettings.tsx, frontend/src/components/Board/Comment/Comment.tsx, frontend/src/components/Board/RegularBoard/index.tsx, frontend/src/components/Board/SplitBoard/Header/index.tsx, frontend/src/components/Boards/MyBoards/ListBoards/index.tsx, frontend/src/components/Boards/MyBoards/ListBoardsByTeam/index.tsx, frontend/src/components/Boards/MyBoards/ListPersonalBoards/index.tsx, frontend/src/components/Boards/MyBoards/index.tsx, frontend/src/components/CardBoard/CardBody/CardBody.tsx, frontend/src/components/CreateBoard/SplitBoard/SubTeamsTab/QuickEditSubTeams.tsx, frontend/src/components/CreateBoard/SplitBoard/SubTeamsTab/TeamSubTeamsConfigurations.tsx, frontend/src/components/Dashboard/RecentRetros/index.tsx
Fixes #986
Fixes #1024 
Fixes #1014 
- Avoid returning unnecessary data in the boards related requests
- Add blur to the card parent element and remove it from the children
- Disable drag and drop while the cards are hidden
- Use floor instead of ceil when calculating the teams
This pull request closes #986 and closes #1024 and closes #1014
=> fix: populates

frontend/.dockerignore, frontend/.gitignore, frontend/.storybook/main.js, frontend/Dockerfile, frontend/next.config.js, frontend/package.json
Relates to #1034
Fixes #1034 
- Add storybook to development pipeline
- Deploy storybook after development build
- Make storybook accessible through `/storybook`
This pull request closes #1034
=> feat: storybook deployment

backend/package-lock.json, backend/src/modules/boards/dto/board.dto.ts, backend/src/modules/boards/dto/column/column.dto.ts, backend/src/modules/cards/dto/card.dto.ts, backend/src/modules/cards/dto/card.item.dto.ts, backend/src/modules/comments/dto/comment.dto.ts, frontend/src/components/Board/AddCardOrComment.tsx, frontend/src/components/Board/Card/CardBoard.tsx, frontend/src/components/Board/Card/CardFooter.tsx, frontend/src/hooks/useVotes.tsx, frontend/src/pages/boards/[boardId].tsx, frontend/src/styles/stitches/partials/colors/primary.colors.ts
- fix class validator
- avoid voting while the cards are hidden
=> fix: class validator

backend/src/modules/boards/utils/clean-board.ts, frontend/src/components/Board/AddCardOrComment.tsx, frontend/src/components/Board/Card/CardBoard.tsx, frontend/src/components/Board/Column/Column.tsx, frontend/src/components/Board/Comment/Comment.tsx, frontend/src/components/Board/Comment/Comments.tsx
- Hide comments text when the card is anonymous and the cards are hidden
- Hide comments section after the hide cards option is enabled
=> fix: clean board and hide comments updating the cards visibility

backend/src/modules/boards/services/delete.board.service.ts
Relates to #942
Fixes #942
- call Archive Slack Service when a board is deleted
This pull request closes #942
=> feat: call archive slack channels service when a board is deleted

frontend/src/components/CreateBoard/RegularBoard/SettingsTabs/index.tsx, frontend/src/components/CreateBoard/SplitBoard/SettingsTabs.tsx, frontend/src/components/Primitives/Tab.tsx, frontend/src/stories/Tab.stories.tsx
Relates to #1053 
Fixes #1053
- Tabs now require a component to render.
This pull request closes #1053
=> fix: dynamic tabs

frontend/src/pages/_app.tsx
=> chore: add maze script

frontend/src/components/Board/AddCardOrComment.tsx, frontend/src/components/CreateBoard/SplitBoard/FakeSettingsTabs/partials/MainBoardCard/index.tsx, frontend/src/components/CreateBoard/SplitBoard/SubTeamsTab/MainBoardCard.tsx, frontend/src/components/Primitives/Checkbox.tsx, frontend/src/components/Primitives/Select.tsx, frontend/src/components/Teams/CreateTeam/ListMembersDialog/index.tsx, frontend/src/components/Users/UserEdit/partials/TeamsDialog/index.tsx, frontend/src/components/Users/UserEdit/partials/UserHeader/index.tsx, frontend/src/pages/boards/newSplitBoard.tsx, frontend/src/stories/Checkbox.stories.tsx, frontend/src/stories/types/PrimitiveTypes.tsx, frontend/src/types/team/team.ts
Relates to #1052 
Fixes #1052 
- Add the Checkbox primitive to Storybook
- Normalize the Checkbox primitive throughout the application
This pull request closes #1052
=> feat: checkbox primitive refactor and story

backend/src/modules/boards/utils/clean-board.ts
- The board request now returns the created by in the anonymous card if the user that makes the request is the author of the card
=> fix: hide comment

backend/src/modules/boards/services/update.board.service.ts, frontend/src/api/boardService.tsx, frontend/src/components/Board/RegularBoard/ParticipantsList/ParticipantCard.tsx/index.tsx, frontend/src/hooks/useParticipants.tsx, frontend/src/types/board/board.user.ts
Relates to #870
- Connected deleting each participant on bin with endpoint.
- Fixed onSettled to return the id's of the added boardUsers.
This pull request closes #870
=> fix: optimistic update onSettled return added users with id

backend/src/modules/communication/applications/slack-communication.application.spec.ts, backend/src/modules/communication/applications/slack-communication.application.ts
Fixes #1073
- keep the size of teams unchanged, even if a channel was not created in `SlackCommunicationApplication@createAllChannels`
@nunocaseiro 
Note: I still not using the factory to create fake data.
This pull request closes #1073
=> fix: add slack channel id to a team

backend/src/libs/utils/generateBoardData.ts, frontend/src/components/Board/AddCardOrComment.tsx, frontend/src/components/Board/Settings/index.tsx, frontend/src/components/CreateBoard/BoardName.tsx, frontend/src/components/Primitives/TextArea.tsx, frontend/src/helper/board/defaultColumns.ts, frontend/src/hooks/useCreateBoard.tsx, frontend/src/pages/boards/newRegularBoard.tsx, frontend/src/pages/boards/newSplitBoard.tsx, frontend/src/schema/schemaCreateBoardForm.ts, frontend/src/schema/schemaUpdateBoardForm.ts, frontend/src/store/createBoard/atoms/create-board.atom.tsx
Relates to #1002 
- Add template to "To improve" column of split board
- Increase maximum of chars of board title to fix bug when editing settings on board created by a cron job
This pull request closes #1002
=> feat: add template for to improve cards

frontend/src/components/Board/Settings/index.tsx, frontend/src/components/Board/Settings/partials/Columns/ColumnBoxAndDelete.tsx
Fixes #1086
- Add more space to edit columns dropdown
This pull request closes #1086
=> fix: added more space between columns

frontend/src/components/Board/AddCardOrComment.tsx, frontend/src/components/Primitives/TextArea.tsx
Fixes #1101 
- The "\n" remains when the user starts typing 
- Change the text area to be a controlled component
This pull request closes #1101
=> fix: new line of the default text

frontend/src/components/Primitives/Tooltip/styles.tsx, frontend/src/stories/Tooltip.stories.tsx
Relates to #1108 
Fixes #1108
- Add the tooltip primitive to storybook
This pull request closes #1108
=> feat: tooltip primitive story

frontend/src/components/Board/Settings/index.tsx
Relates to #1117 
Fixes #1117
- Fix dialog form scroll and submit on board settings
This pull request closes #1117
=> fix: dialog form scroll and submit

backend/src/modules/boards/services/update.board.service.ts
- Fix the board number in the message that is sent when the responsible is changed
=> fix: board number when the responsible is changed

backend/src/modules/azure/services/auth.azure.service.ts
Fixes condition to get the azure token, the condition was inverted
=> fix(azure): if statement to get token

backend/src/modules/users/repository/user.repository.ts
Relates to #1157 
Fixes #1157
- Get users from database with the flag isAnonymous false or undefined
This pull request closes #1157
=> fix: get non anonymous users

backend/src/libs/utils/generateBoardData.ts, backend/src/modules/communication/applications/slack-communication.application.ts, backend/src/modules/communication/dto/team.dto.ts, backend/src/modules/communication/dto/types.ts, frontend/src/hooks/useCreateBoard.tsx
Relates to #1143
- Change the sub-board name to "Sub team `#` board
- Change the main split slack message replacing "Sub team board `#`" to "Sub team `#`"
This pull request closes #1143
=> refactor: change sub board name

frontend/src/components/CardBoard/CardBody/CardTitle.tsx, frontend/src/pages/boards/[boardId].tsx
Fixes #1173 
- Subboard is merged banner
This pull request closes #1173
=> fix: merged subboard banner

backend/src/modules/boards/repositories/board.repository.interface.ts, backend/src/modules/boards/repositories/board.repository.ts, backend/src/modules/boards/services/update.board.service.ts, backend/src/modules/communication/applications/slack-merge-board.application.ts
Fixes #1170 
- add await on the board updates methods
- add await on send message methods in the merge board slack application  
This pull request closes #1170
=> fix: merge board last message

backend/src/modules/teams/repositories/team.repository.ts
Fixes #1195 
- Remove populate board path from team repository
This pull request closes #1195
=> fix: remove populate path fro boards on team repo

frontend/src/pages/boards/newRegularBoard.tsx, frontend/src/pages/boards/newSplitBoard.tsx
Relates to #1197
Fixes #1197
- Fix the design layouts in the "create board" pages
This pull request closes #1197
=> fix: create board page design

backend/src/modules/auth/auth.module.ts, backend/src/modules/auth/auth.providers.ts, backend/src/modules/auth/interfaces/types.ts, backend/src/modules/auth/repository/reset-password.repository.interface.ts, backend/src/modules/auth/repository/reset-password.repository.ts, backend/src/modules/auth/services/create-reset-token.auth.service.ts
Relates to 
- #1212 
- Add reset-password repository
This pull request closes #1212
=> feat: add reset-password repository

.github/pull_request_template.md
Changed template to use @geomarb suggestion.
The fields: relates to, fixes and closes will display the name of the issue instead of only the issue number
- Changed the PR Template to better display the issue.
=> feat: update pull request template

backend/src/modules/boards/services/update.board.service.spec.ts
- Fix new test file with old board user repository. Replaced with boardUser service.
=> fix: import error

.github/ISSUE_TEMPLATE/test_request.md
Relates to:
- #1253
- Add new issue template for tests
- #1253
=> feat: add test_request issue

backend/src/modules/boards/services/delete.board.service.spec.ts, backend/src/modules/boards/services/delete.board.service.ts
Relates to:
- #1228 
- Add delete.board.service.spec.ts
- Add unit tests for the delete method
- Add unit tests for the deleteBoardsByTeamId method
- #1228
=> test: delete board service test

backend/.env.example, frontend/.env.example
=> chore: add missing variables

backend/src/modules/boards/services/create.board.service.ts
=> fix: split teams

backend/src/libs/test-utils/mocks/factories/communication/UserRoleType-factory.mock.ts, backend/src/libs/test-utils/mocks/factories/communication/boardType-factory.mock.ts, backend/src/libs/test-utils/mocks/factories/communication/changeResponsible.mock.ts, backend/src/libs/test-utils/mocks/factories/communication/mergeBoardType.mock.ts, backend/src/modules/communication/producers/slack-add-user-channel.producer.spec.ts, backend/src/modules/communication/producers/slack-archive-channel.producer.spec.ts, backend/src/modules/communication/producers/slack-archive-channel.producer.ts, backend/src/modules/communication/producers/slack-communication.producer.spec.ts, backend/src/modules/communication/producers/slack-merge-board.producer.spec.ts, backend/src/modules/communication/producers/slack-responsible.producer.spec.ts
Relates to:
- #1275 
- Add tests to all communication producers
- Add mocks to prevent duplicate code
This pull request closes #1275
=> test: communication producers

backend/src/modules/cards/services/create.card.service.spec.ts
Relates to:
- #1280 
-Add create.card.service tests
This pull request closes #1280
=> test: create card service

frontend/src/components/CreateBoard/SplitBoard/FakeSettingsTabs/partials/MainBoardCard/index.tsx, frontend/src/components/CreateBoard/SplitBoard/SubTeamsTab/MainBoardCard.tsx, frontend/src/components/Teams/TeamsList/TeamItem/TeamBoards/TeamBoards.tsx
Fixes:
- #1277 
- Size of minus icon fixed
- Color of plus sign fixed
This pull request closes #1277
=> fix: fix minus size and plus color

backend/src/modules/users/applications/delete-user.use-case.ts, frontend/src/api/teamService.tsx, frontend/src/components/Board/Card/CardBoard.tsx, frontend/src/components/Teams/Team/TeamMemberItem/TeamMemberItem.tsx, frontend/src/components/Users/UsersList/UsersList.tsx, frontend/src/hooks/useTeam.tsx, frontend/src/hooks/useUser.tsx, frontend/src/types/team/useTeam.ts
Fixes:
- #1286
- #1285
- #1163
- Fix the change of a user role in the team's creation page
- Fix the flick on the team user's list when the team or board role changes
- Fix the deletion of a user
- Fix the user's list update when the user is deleted
- Add `user-select : none` when the cards are hidden
This pull request closes #1286 and closes #1285 and closes #1163
=> fix: recent bugs

backend/src/libs/exceptions/updateFailedBadRequestException.ts, backend/src/libs/repositories/mongo/mongo-generic.repository.ts, backend/src/modules/cards/controller/cards.controller.ts, backend/src/modules/cards/interfaces/applications/delete.card.application.interface.ts, backend/src/modules/cards/interfaces/services/delete.card.service.interface.ts, backend/src/modules/cards/repository/card.repository.interface.ts, backend/src/modules/cards/repository/card.repository.ts, backend/src/modules/cards/services/delete.card.service.ts
Relates to:
- #1297
Fixes:
- #1297
- Replace `findOneAndUpdate` by `updateOneByField`
This pull request closes #1297
=> fix: delete cards

backend/src/modules/cards/services/delete.card.service.ts, backend/src/modules/votes/interfaces/services/create.vote.service.interface.ts, backend/src/modules/votes/interfaces/services/delete.vote.service.interface.ts, backend/src/modules/votes/services/create.vote.service.ts, backend/src/modules/votes/services/delete.vote.service.ts, frontend/src/hooks/useCards.tsx
Relates to:
- #1302 
- Refactor of the code on create and delete votes service
- Fix handling of errors on delete card service, when deleting votes fails
=> refactor: votes services

.github/CONTRIBUTING.md
- Changes Contributing Guidelines title, replacing the old project name (Divide & Conquer) with the current one (SPLIT)
=> docs: update contribution guidelines project name

frontend/.storybook/manager.js, frontend/next.config.js
=> fix: storybook in dev and prod env

backend/src/modules/boards/services/update.board.service.ts
Relates to:
- #1355 
Fixes:
- #1355 
- Add channel id to message
This pull request closes #1355
=> fix: channel id missing

frontend/.storybook/preview.js
Relates to:
- #1441
Fixes:
- #1441
- Removed Deleted Import File
This pull request closes #1441
=> fix: removed deleted import

frontend/src/components/auth/LoginForm/index.tsx
Relates to:
- #1449 
Fixes:
- #1449 
- When logging in with SSO, the page no longer triggers the form validation
- Also it disables the SSO Button and displays loading dots to give the user some feedback
This pull request closes #1449
=> fix: sso trigger validations

frontend/src/components/Board/Column/Column.tsx, frontend/src/components/Board/Column/partials/OptionsMenu/index.tsx, frontend/src/components/Board/Column/partials/OptionsMenu/styles.tsx
Relates to:
- #1451
Fixes:
- #1451
- Fixed Colors in Regular Boards
- Also used the Badge Primitive in the Board Columns
This pull request closes #1451
=> fix: card colors position

frontend/src/hooks/auth/useSignUp.tsx
- Remove braces to return the function result.
=> fix: query function without return

frontend/src/components/Board/Timer/index.tsx, frontend/src/components/Board/Timer/styles.tsx
Relates to:
- #1465 
Fixes:
- #1465 
- Fixed Timer Design Bug
This pull request closes #1465 , #1417
=> fix: timer design

backend/src/modules/communication/applications/slack-communication.application.ts
Fixes:
- #1514
- Update confluence link
This pull request closes #1514
=> fix: #1514 - update retro link

.github/workflows/build_docker.yaml
- Split migration
- Change CI/CD to push docker image to the new container registry
=> feat: update ci/cd to push docker image to the new container registry

.github/workflows/deploy_backend_frontend.yml, .github/workflows/on_call_deploy.yaml, infrastructure/values/development.yaml, infrastructure/values/production.yaml
- change split domain in helm chart
- clean up workflow deploy files
=> feat: change split domain

backend/src/libs/test-utils/mocks/factories/azure-user-factory.ts, backend/src/modules/azure/azure.module.ts, backend/src/modules/azure/azure.providers.ts, backend/src/modules/azure/constants.ts, backend/src/modules/azure/interfaces/schedules/synchronize-ad-users.cron.azure.use-case.interface.ts, backend/src/modules/azure/interfaces/services/auth.azure.service.interface.ts, backend/src/modules/azure/schedules/synchronize-ad-users.cron.azure.use-case.spec.ts, backend/src/modules/azure/schedules/synchronize-ad-users.cron.azure.use-case.ts, backend/src/modules/azure/services/auth.azure.service.ts, backend/src/modules/users/applications/get-all-users-include-deleted.use-case.spec.ts, backend/src/modules/users/applications/get-all-users-include-deleted.use-case.ts, backend/src/modules/users/constants.ts, backend/src/modules/users/repository/user.repository.interface.ts, backend/src/modules/users/repository/user.repository.ts, backend/src/modules/users/users.module.ts, backend/src/modules/users/users.providers.ts
Relates to:
- #1594
- synchronization of users between app and azure AD via cron
This pull request closes #1594
=> feat: issue 1594 synchronize users ad app

backend/src/modules/teams/services/get.team.service.ts
Fixes:
- #1606 
- Fix users teams not being presented
This pull request closes #1606
=> fix: query team id

backend/src/modules/azure/schedules/synchronize-ad-users.cron.azure.use-case.ts
Fixes:
- #1608 
- Fix user e-mail domain filter
This pull request closes #1608
=> fix: synchronization user email domain filter

.github/workflows/tests_backend_frontend.yml, backend/src/modules/azure/services/auth.azure.service.ts, backend/src/modules/boards/repositories/board.repository.ts, backend/src/modules/boards/utils/populate-board.ts, backend/src/modules/teams/repositories/team.repository.ts, frontend/.env.example, frontend/next.config.js, frontend/src/components/Board/Card/CardFooter.tsx, frontend/src/components/Board/Column/partials/SortMenu.tsx, frontend/src/components/Board/Comment/PopoverSettings.tsx, frontend/src/components/Boards/MyBoards/ListBoardMembers/FilterBoardMembers/index.tsx, frontend/src/components/CardBoard/CardBody/CardEnd.tsx, frontend/src/components/CardBoard/CardBody/CardTitle.tsx, frontend/src/components/CardBoard/CardBody/CardTitle/index.tsx, frontend/src/components/CardBoard/CardBody/CardTitle/partials/Title/index.tsx, frontend/src/components/Primitives/Avatars/AvatarGroup/AvatarGroup.tsx, frontend/src/components/Primitives/Tooltips/Tooltip/Tooltip.tsx, frontend/src/components/RecoilDevTools/RecoilDevTools.tsx, frontend/src/components/Sidebar/Header/Header.spec.tsx, frontend/src/components/Sidebar/Header/Header.tsx, frontend/src/components/Sidebar/Sidebar.spec.tsx, frontend/src/components/Sidebar/Sidebar.tsx, frontend/src/components/Sidebar/types.ts, frontend/src/components/Teams/Team/TeamMemberItem/TeamMemberItem.tsx, frontend/src/components/Users/UsersList/UserItem/UserItem.tsx, frontend/src/components/layouts/Layout/Layout.tsx, frontend/src/types/user/user.ts, infrastructure/values/development.yaml, infrastructure/values/production.yaml
Fixes:
- #1613
- Show user's photo instead of generic user icon
This pull request closes #1613
=> feat: show user avatar photo

.github/workflows/deploy_backend_frontend.yml, .github/workflows/tests_backend_frontend.yml, frontend/Dockerfile
Fixes:
- failed docker build
- change AZURE_STORAGE_HOSTNAME from secret to var
=> chore: change AZURE_STORAGE_HOSTNAME from secret to var

backend/src/libs/test-utils/mocks/factories/azure-user-factory.ts, backend/src/modules/azure/dto/azure-user.dto.ts, backend/src/modules/azure/interfaces/services/auth.azure.service.interface.ts, backend/src/modules/azure/schedules/synchronize-ad-users.cron.azure.use-case.spec.ts, backend/src/modules/azure/schedules/synchronize-ad-users.cron.azure.use-case.ts, backend/src/modules/azure/services/auth.azure.service.ts, backend/src/modules/users/utils/sortings.ts
- Fix applied to prevent user's from being created when receiving invalid data for 'name' from AD
=> fix: user name in ad synchronization
