frontend/api/boardService.tsx
frontend/components/Board/Card/AddCard.tsx
frontend/components/Board/Card/CardFooter.tsx
frontend/components/HOC/requireAuthentication.tsx
frontend/components/Title/InputTitle.tsx
frontend/helper/board/votes.ts
frontend/hooks/useBoard.tsx
frontend/pages/boards/[boardId].tsx
frontend/store/slicer/boardSlicer.tsx
frontend/store/store.tsx
frontend/types/board/useBoard.ts
frontend/types/board/vote/vote.dto.ts
frontend/utils/fetchData.tsx

Relates to #88
- Upvote and downvote in the card footer
- Enable/disable voting based on board max votes
- Request methods to call the api in order to create or remove a vote
- Votes count methods and they are already prepared to include the card group votes
This pull request is intended to close #88

feat: upvote, downvote and count votes

---

backend/src/infrastructure/config/jwt.register.ts
backend/src/libs/dto/param/pagination.params.ts
backend/src/modules/auth/auth.module.ts
backend/src/modules/auth/controller/auth.controller.ts
backend/src/modules/azure/services/auth.azure.service.ts
backend/src/modules/boards/applications/get.board.application.ts
backend/src/modules/boards/boards.module.ts
backend/src/modules/boards/controller/boards.controller.ts
backend/src/modules/boards/interfaces/applications/get.board.application.interface.ts
backend/src/modules/boards/interfaces/boards-page.interface.ts
backend/src/modules/boards/interfaces/findQuery.ts
backend/src/modules/boards/interfaces/services/get.board.service.interface.ts
backend/src/modules/boards/schemas/board.schema.ts
backend/src/modules/boards/services/create.board.service.ts
backend/src/modules/boards/services/get.board.service.ts
backend/src/modules/teams/applications/get.team.application.ts
backend/src/modules/teams/interfaces/applications/get.team.application.interface.ts
backend/src/modules/teams/services/get.team.service.ts
backend/src/modules/users/dto/user.dto.ts
backend/test/auth/auth.controller.spec.ts
backend/test/boards/boards.controller.spec.ts

Relates to #123
- Method in auth controller to retrieve some statistics about the authenticated user
- Get all boards service method depending of the user's role and atual page in the frontend. 
- If dashboard -> all boards of user of the last 3 months
- if boards page and the user is super admin -> all boards 
- if boards page and the user is not super admin -> all boards of user
- Get all boards with pagination
This pull request is intended to close #123

feat: dashboard statistics and get all boards with pagination

---

frontend/api/boardService.tsx
frontend/components/CreateBoard/Configurations/BoardConfigurations.tsx
frontend/components/CreateBoard/Content.tsx
frontend/components/CreateBoard/SettingsTabs.tsx
frontend/components/CreateBoard/SubTeamsTab/SubCardBoard.tsx
frontend/components/Primitives/Switch.tsx
frontend/components/icons/Check.tsx
frontend/types/board/useBoard.ts

Relates to #141
- Configurations tab
- Create board request
This pull request is intended to close #141

feat: create board and configurations

---

backend/src/libs/enum/board.roles.ts
backend/src/libs/utils/ignored_users.json
backend/src/modules/boards/controller/boards.controller.ts
backend/src/modules/boards/dto/board.dto.ts
backend/src/modules/boards/dto/board.user.dto.ts
backend/src/modules/boards/interfaces/applications/get.board.application.interface.ts
backend/src/modules/boards/interfaces/findQuery.ts
backend/src/modules/boards/interfaces/services/get.board.service.interface.ts
backend/src/modules/boards/schemas/board.schema.ts
backend/src/modules/boards/schemas/board.user.schema.ts
backend/src/modules/boards/services/create.board.service.ts
backend/src/modules/boards/services/get.board.service.ts
backend/src/modules/teams/applications/create.team.application.ts
backend/src/modules/teams/applications/get.team.application.ts
backend/src/modules/teams/controller/team.controller.ts
backend/src/modules/teams/interfaces/applications/create.team.application.interface.ts
backend/src/modules/teams/interfaces/applications/get.team.application.interface.ts
backend/src/modules/teams/interfaces/services/create.team.service.interface.ts
backend/src/modules/teams/interfaces/services/get.team.service.interface.ts
backend/src/modules/teams/providers.ts
backend/src/modules/teams/services/create.team.service.ts
backend/src/modules/teams/services/get.team.service.ts
backend/tsconfig.json

Relates to #137
- create the `board_users` in the main board that are participating in the board team
- get stakeholders method
- get teams of user and users of team
- get board

refactor: create board users from team,  create team user, get teams methods

---

backend/package.json
backend/src/app.module.ts
backend/src/infrastructure/config/config.module.ts
backend/src/infrastructure/config/configuration.ts
backend/src/infrastructure/config/interfaces/configuration.interface.ts
backend/src/infrastructure/database/mongoose.module.ts
backend/src/modules/auth/applications/create-reset-token.auth.application.ts
backend/src/modules/auth/auth.module.ts
backend/src/modules/auth/auth.providers.ts
backend/src/modules/auth/controller/auth.controller.ts
backend/src/modules/auth/interfaces/applications/create-reset-token.auth.application.interface.ts
backend/src/modules/auth/interfaces/services/create-reset-token.auth.service.interface.ts
backend/src/modules/auth/interfaces/types.ts
backend/src/modules/auth/schemas/reset-password.schema.ts
backend/src/modules/auth/services/create-reset-token.auth.service.ts
backend/src/modules/mailer/mailer.module.ts
backend/test/auth/auth.controller.spec.ts
package-lock.json
package.json

Relates to  #108
-  Reset token schema and create and update method implemented.
-  Mailer module was used to send an email with a link to reset the user password .
- A 1 minute timer was implemented to the reset password flow to prevent extra requests from the same user ( there might be a better way to do this ) 
- Env files updated with mailer module options

feat: reset token and mailer

---

frontend/components/auth/LoginForm/index.tsx

Relates to #209
- Create a `useEffect` to avoid show the default message from enum
- Basically, when toastr is open, the code sended to get the message from enum is `-1`, returning the default message from that enum.
This pull request closes #209

[FIX]: Wrong Feedback on first login attempt 

---

frontend/src/components/auth/LoginForm/styles.tsx

Fixes #245
- Spacing between separator and sso icons
This pull request closes #245

[FIX]: SSO icons margin

---

backend/src/modules/azure/services/auth.azure.service.ts

Fixes #265 
- Send the unique name or the email to check if the user exists in ad
This pull request closes #265

fix: check user email or unique name in AD

---

frontend/src/components/CreateBoard/SubTeamsTab/SubCardBoard.tsx

Fixes #272 
- Blocking the function to change the responsible if the board as only 1 or less members
- Added a disable state to the button
This pull request closes #272

[FIX]: Responsible Lottery is freezing the page when the group only contains 1 user.

---

frontend/src/components/Board/Card/CardFooter.tsx
frontend/src/components/CardBoard/CardAvatars.tsx
frontend/src/components/Primitives/Avatar.tsx
frontend/src/hooks/useAvatarColor.tsx

Fixes #260 
- Dashboard page: First load
- Dashboard page: second load
- Boards page: First load
- Boards page: Second load
Proposed Changes
- Colors of each user are being saved to Local Storage
- Show the same colors every time the page is loaded
This pull request closes #260

[FIX]: Avatar color

---

frontend/src/components/Boards/MyBoards/styles.tsx

Fixes #280
-Resize the  size of the scrolling window in the Boards Page
This pull request closes #280

[FIX]: Resize of the scrolling window in the boards page

---

frontend/src/components/Board/Settings/index.tsx

Fixes #282 
- Set the maxVotes to undefined instead of empty.
This pull request closes #282

fix: switchs

---

backend/src/modules/cards/services/update.card.service.ts
backend/src/modules/comments/services/delete.comment.service.ts
backend/src/modules/comments/services/update.comment.service.ts
frontend/src/components/Board/Card/CardBoard.tsx
frontend/src/components/Board/Card/CardItem/CardItem.tsx
frontend/src/components/Board/Comment/Comment.tsx

Fixes #318 
- Prepare frontend and backend to allow users edit only their own comments 
This pull request closes #318

[FIX]: Edit cards from others

---

frontend/src/pages/boards/[boardId].tsx

Fixes #338 
- Only show the button if the user created the board
This pull request closes #338

[FIX]: Only show the board settings for the user that created the board

---

frontend/src/components/Dashboard/RecentRetros/ListOfCards.tsx
frontend/src/components/loadings/LoadingPage/styles.tsx

Fixes #358
- Change the pageLoading component for the dotsLoading component
- Giving z-index to pageLoading to fix the overlap bug
This pull request closes #358

[BUG]: Lazy loading indicator in the dashboard

---

frontend/src/pages/boards/[boardId].tsx

Fixes #389 
- when the board is already merged don't show the button
This pull request closes #389

[BUG]: lock boardSettings button with subboard merge

---

backend/src/modules/azure/controller/azure.controller.ts
backend/src/modules/boards/services/delete.board.service.ts
backend/src/modules/teams/services/get.team.service.ts
frontend/src/components/CardBoard/CardBody/CardBody.tsx
frontend/src/components/CardBoard/CardBody/CardEnd.tsx

Relates to #407
- User who has just been created and is a member can't delete existing boards
- Users with Stakeholder, admin, SuperAdmin have permissions to delete boards
- Users who created boards also have permission to delete their own boards
@CatiaBarroco-xgeeks @dsousa12 @miguel-felix1 
This pull request closes #407

[BUG]: users permissions to delete boards

---

frontend/src/components/Board/AddCardOrComment.tsx

Relates to #411
-if we try to change a comment to an empty space it gives an error but it doesn't break the site
This pull request closes #411

 [BUG] Editing a comment to empty crashes the website

---

frontend/src/components/Board/AddCardOrComment.tsx

Fixes #411 
- user cannot edit a comment for an empty comment
This pull request closes #411

[BUG] Editing a comment to empty crashes the website

---

frontend/src/components/Board/AddCardOrComment.tsx

Fixes #421
-the user cannot put empty cards or empty comments
This pull request closes #421

[BUG]: Editing a card title to empty crashes the website

---

frontend/src/components/Board/Card/CardFooter.tsx

Relates to #428
- just fill the icon when the comments are open
@f-morgado 
This pull request closes #428

[BUG] Comment icon remains in clicked state 

---

backend/src/libs/utils/boardVotesIdHidden.ts
backend/src/modules/boards/services/get.board.service.ts
backend/src/modules/votes/controller/votes.controller.ts
backend/src/test/boards/get.board.service.spec.ts

Relates to #378 
-Users' id is hidden when he votes so that other can't see who placed votes on the card (beside themselves)
This pull request closes #378

[FEATURE]: Hide id from users when they vote on the cards

---

frontend/src/components/Board/Card/CardFooter.tsx

Fixes #436 
- disable the upvote/downvote button while the request wasnt fullfilled.
- Prevents non stopping spam while vote request wasnt updated.
@CatiaBarroco-xgeeks 
This pull request closes #436

[BUG]: disable button between orders

---

frontend/src/components/Board/Card/CardFooter.tsx

Fixes #439 
-if the user does not have votes on that card, the downvotes button will appear disabled
@miguel-felix1 
This pull request closes #439

[BUG]: disable button to remove non-user votes 

---

backend/src/modules/cards/services/delete.card.service.ts

Fixes #441
- update information when cardGroup only has 1 item
@joaosantos99 @CatiaBarroco-xgeeks 
This pull request closes #441

[BUG] Deleting merged cards

---

frontend/src/components/Board/Settings/index.tsx
frontend/src/pages/boards/[boardId].tsx

Relates to #447 
- The responsible can change to another responsible 
@f-morgado  @joaosantos99  @miguel-felix1 
This pull request closes #447

[FEATURE]: Responsible can change to another

---

backend/src/app.module.ts
backend/src/modules/communication/communication.module.ts
backend/src/modules/communication/communication.providers.ts
backend/src/modules/communication/services/slack-disabled-communication.service.ts

Relates to #452 
Fixes #343
Since the Communication module should be loaded only if the SLACK_ENABLE environment variable is set to "true". This module should have the responsibility to check it and load accordingly, for that:
- registers the queue only if necessary
- instantiate only the necessary classes
- provide a class service in case the SLACK_ENABLE is set to "false" in order not to break the use of "ExecuteCommunicationService"
- move Queue Module to app module imports, this module should load independent of the communication module. From now on the **REDIS environment variables are mandatory**.
@f-morgado @CatiaBarroco-xgeeks 
This pull request closes #452

chore: add  communication service for slack disabled

---

frontend/src/components/Board/AddCardOrComment.tsx
frontend/src/components/CreateBoard/SubTeamsTab/MainBoardCard.tsx
frontend/src/components/Primitives/Checkbox.tsx

Fixes #454 
- change the condicion on chackbox primitives
- the user can add anonymous cards
@mourabraz 
This pull request closes #454

[BUG] Post card as Anonymous 

---

frontend/src/pages/boards/[boardId].tsx

Relates to #382 
-if the user does not belong to the board, he will not be able to enter it
This pull request closes #382

[SUGGESTION]: Checking if the users is from the sub-team

---

frontend/package-lock.json
frontend/package.json
frontend/src/hooks/useSocketIO.ts
frontend/src/pages/boards/[boardId].tsx
frontend/src/pages/dashboard/index.tsx

Fixes #466 
Fixes #467 
- Change socketIO hook in order to avoid a user from having multiple socket connections on the same board
- Update next-auth package
This pull request closes #466 and #467

refactor(socket): prevent multiple connections and update next auth

---

frontend/src/schema/schemaCreateBoardForm.ts
frontend/src/schema/schemaUpdateBoardForm.ts

Fixes #462 
- if the responsible tries to update the board name to an empty name, it will return an error and will not let update the board
This pull request closes #462

[BUG] Sub-board Name

---

frontend/src/components/Board/Card/CardBoard.tsx
frontend/src/components/Board/Card/CardFooter.tsx
frontend/src/components/Board/DragDropArea/index.tsx

Fixes #463 
- it is only possible to merge and unmerge cards if the hideCards board option is false
This pull request closes #463

[BUG] Comment on Hidden card 

---

frontend/src/schema/schemaRegisterForm.ts
frontend/src/schema/schemaResetPasswordForm.ts

Fixes #481
- Change the "not word" character class to a multiple negate sets because in regex underscore is in the word set
This pull request closes #481

[FIX] password regex

---

frontend/src/components/Sidebar/partials/Content/index.tsx

Relates to #512 
- Disable teams button from sidebar menu
This pull request closes #512

[FEATURE]: disable teams button from sidebar menu

---

frontend/src/components/Teams/CreateTeam/ListCardsMembers/index.tsx
frontend/src/pages/teams/new.tsx
frontend/src/styles/pages/boards/new.styles.tsx

Relates to #518 
- Add cancel and create team buttons layout to the create new team page.
This pull request closes #518

[FEATURE]: add form buttons to create team page

---

frontend/src/components/Board/Settings/index.tsx

Relates to #483
- Reset the info changes when the user cancel the board settings panel
@f-morgado @CatiaAntunes96 @joaosantos99 
This pull request closes #483

[BUG]: Board Settings Info cancel button to reset info

---

frontend/src/components/Teams/CreateTeam/CardEnd.tsx
frontend/src/components/Teams/CreateTeam/CardMember/index.tsx
frontend/src/components/Teams/CreateTeam/ListCardsMembers/index.tsx
frontend/src/components/Teams/CreateTeam/ListCardsMembers/styles.tsx
frontend/src/components/Teams/CreateTeam/ListMembers/index.tsx
frontend/src/components/Teams/CreateTeam/TeamName.tsx
frontend/src/components/Teams/CreateTeam/index.tsx
frontend/src/pages/teams/new.tsx
frontend/src/store/team/atom/team.atom.tsx
frontend/src/types/team/team.user.ts

Relates to #544 
- Instead of just keep a list of objects with userId and role, now the object is keeping the whole user and his role (they are needed in the card member)
-The members list is initialise with the user that is creating the team with the role as 'Admin'. This is being done at the same time that the prop isChecked is being added to each user.  
-When the members are added, the cards with each user are rendered.
This pull request closes #544

[FEATURE]: render members card

---

frontend/src/components/Teams/CreateTeam/TipBar/index.tsx

Relates to #545 
- When there are 2 or more users in the list of members, the newbee tip shows
This pull request closes #545

[FEATURE]: add newbee tip if members are > 1

---

frontend/src/components/Teams/CreateTeam/ListCardsMembers/index.tsx
frontend/src/components/Teams/CreateTeam/ListMembers/index.tsx

Relates to #545 
- The 'Add member' button is also rendered on top if the user as to scroll
This pull request closes #545

[FEATURE]: show btn if scroll exists

---

frontend/src/components/CardBoard/CardBody/CardBody.tsx

Relates to #556
- Only the main boards card are shown in the list of boards page by default.
This pull request closes #556

[REFACTOR]: list boards without showing subboards 

---

frontend/src/components/Board/Header/index.tsx
frontend/src/components/CardBoard/CardAvatars.tsx
frontend/src/components/CardBoard/styles.tsx

Relates to #555 
- If the user is in a board or sub-board page, he can click on the avatars icon to see all the users in that board. If he clicks again on an avatar, the list goes back to the default (only 3 avatars)
This pull request closes #555

[FEATURE]: show boards members 

---

frontend/src/components/CardBoard/styles.tsx

Fixes #562
- Padding removed from buttonIcon
This pull request closes #562

[BUG]: remove space between avatar icons

---

frontend/src/components/Boards/MyBoards/index.tsx
frontend/src/components/layouts/DashboardLayout/index.tsx
frontend/src/components/layouts/Layout/index.tsx
frontend/src/pages/boards/new.tsx

Fixes # 558
- When clicking on the X or cancel button of the 'Create new board' page, instead of going back to the previous route, the user is redirected to the list boards page.
This pull request closes #558

[BUG] Cancel/X Buttons 

---

frontend/src/components/Sidebar/partials/Content/index.tsx
frontend/src/components/layouts/DashboardLayout/index.tsx
frontend/src/components/layouts/Layout/index.tsx
frontend/src/pages/users/index.tsx
frontend/src/utils/routes.ts

Fixes #
- Added User page with title layout
- The "Users" button on the sidebar redirects to the users page
This pull request closes #595

feat: added users page layout

---

backend/src/modules/teams/interfaces/users-with-teams.interface.ts
backend/src/modules/teams/services/get.team.service.ts
frontend/src/api/userService.tsx
frontend/src/components/Users/UsersList/index.tsx
frontend/src/components/Users/UsersList/partials/CardUser/CardBody.tsx
frontend/src/components/Users/UsersList/partials/CardUser/CardEnd.tsx
frontend/src/components/Users/UsersList/partials/CardUser/CardTitle.tsx
frontend/src/components/Users/UsersList/partials/CardUser/DeleteUser.tsx
frontend/src/components/Users/UsersList/partials/CardUser/EditUser.tsx
frontend/src/components/Users/UsersList/partials/CardUser/SuperAdmin.tsx
frontend/src/components/Users/UsersList/partials/ListOfCards/index.tsx
frontend/src/pages/users/index.tsx
frontend/src/store/user/atoms/user.atom.tsx
frontend/src/types/user/user.ts

- user cards containing: name, email, number of teams, switch to change Super Admin role, edit button and delete button
- number of registered users on the platform
- search input to search for users
- in the users with teams API, removed the "isSAdmin" from the $unset field, because we need this field for the cards
This pull request closes #597

feat: user card on the list

---

frontend/src/components/Board/Card/CardBoard.tsx
frontend/src/components/Board/Comment/Comment.tsx

Fixes #656
- Fix large cards
- Add word break and white-space css prop in the comments and in the cards text
This pull request closes #656

fix: large cards

---

backend/src/libs/guards/superAdmin.guard.ts
backend/src/libs/repositories/interfaces/base.repository.interface.ts
backend/src/libs/repositories/mongo/mongo-generic.repository.ts
backend/src/modules/teams/interfaces/users-with-teams.interface.ts
backend/src/modules/users/applications/update.user.application.ts
backend/src/modules/users/controller/users.controller.ts
backend/src/modules/users/dto/update.user.dto.ts
backend/src/modules/users/interfaces/applications/update.user.service.interface.ts
backend/src/modules/users/interfaces/services/update.user.service.interface.ts
backend/src/modules/users/repository/user.repository.interface.ts
backend/src/modules/users/repository/user.repository.ts
backend/src/modules/users/services/update.user.service.ts
backend/src/modules/users/swagger/update.superadmin.swagger.ts
frontend/src/__tests__/index.test.tsx
frontend/src/api/userService.tsx
frontend/src/components/Board/Settings/partials/ConfigurationSettings/SwitchThumbComponent.tsx
frontend/src/components/Board/Settings/partials/ConfigurationSettings/index.tsx
frontend/src/components/Primitives/Switch.tsx
frontend/src/components/Users/UsersList/partials/CardUser/CardBody.tsx
frontend/src/components/Users/UsersList/partials/CardUser/CardEnd.tsx
frontend/src/components/Users/UsersList/partials/CardUser/EditUser.tsx
frontend/src/components/Users/UsersList/partials/CardUser/SuperAdmin.tsx
frontend/src/components/Users/UsersList/partials/ListOfCards/index.tsx
frontend/src/hooks/useUser.tsx
frontend/src/hooks/useUserUtils.tsx
frontend/src/pages/users/[userId].tsx
frontend/src/pages/users/index.tsx
frontend/src/store/user/atoms/user.atom.tsx
frontend/src/types/user/user.ts

#599 
As Super Admin:
As member:
- As a super admin the switch button should be visible and editable. This action makes a request to the backend in order to change the user role in the app. 
- The edit button and when the user clicks in the user's name should redirect to the user details. 
- The delete button should be present and this will be done in issue https://github.com/xgeekshq/split/issues/600. 
- Both icons and user's name must have a hover behaviour.
- A member only sees the user teams count and which user is an admin.
@GuiSanto 
This pull request closes #599

feat: user card actions

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/CreateBoard/SettingsTabs.tsx
frontend/src/components/CreateBoard/SubTeamsTab/MainBoardCard.tsx
frontend/src/components/CreateBoard/SubTeamsTab/SelectTeam/index.tsx
frontend/src/components/CreateBoard/SubTeamsTab/SelectTeam/styles.tsx
frontend/src/components/CreateBoard/SubTeamsTab/TeamSubTeamsConfigurations.tsx
frontend/src/components/CreateBoard/fake/FakeSettingsTabs/partials/MainBoardCard/index.tsx
frontend/src/components/CreateBoard/fake/FakeSettingsTabs/partials/TeamTab/index.tsx
frontend/src/components/CreateBoard/fake/FakeSettingsTabs/partials/TeamTab/styles.tsx
frontend/src/components/Primitives/Checkbox.tsx
frontend/src/components/Primitives/Select.tsx
frontend/src/pages/boards/new.tsx
frontend/src/pages/teams/[teamId].tsx
frontend/src/pages/teams/index.tsx
frontend/src/pages/teams/new.tsx
frontend/src/schema/schemaCreateBoardForm.ts
frontend/src/store/createBoard/atoms/create-board.atom.tsx
frontend/src/store/team/atom/team.atom.tsx
frontend/src/utils/constants.ts

Relates to #663 
Fixes #577 
Fixes #580 
- Add a select with teams that the user is part of. If the user is super Admin, he can view all the teams.
- When the user selects a team, it's validated if he is a team admin, a stakeholder or super admin, and if the team has the minimum number of members to form subteams. If one of this conditions fails, a message error is displayed and the user can select another team.
- The joi schema validates if a team is selected. This prevents the user of creating a board without a team, if he clicks on the create button. 
- Fix: Remove error message when the page is refreshed.
- Fix: Cancel board create button bug fixed. The button is always accessible to the user. 
- Fix: Max Votes input only accepts integers
This pull request closes #663 #577 #580

feat: change team on create board

---

backend/src/modules/teams/interfaces/services/get.team.service.interface.ts
backend/src/modules/teams/repositories/team-user.repository.interface.ts
backend/src/modules/teams/repositories/team-user.repository.ts
backend/src/modules/teams/services/get.team.service.ts
backend/src/modules/users/applications/get.user.application.ts
backend/src/modules/users/controller/users.controller.ts
backend/src/modules/users/interfaces/applications/get.user.application.interface.ts
backend/src/modules/users/interfaces/services/get.user.service.interface.ts
backend/src/modules/users/repository/user.repository.interface.ts
backend/src/modules/users/repository/user.repository.ts
backend/src/modules/users/services/get.user.service.ts

#594 
Relates to #602 
-A lazy loading strategy should be implemented to avoid fetching all the platform users at the same time. So the user can fetch, for example, 15 at a time and more 15 when the scroll reaches its end.
@GuiSanto 
This pull request closes #602

feat: users lazy loading backend

---

frontend/src/api/userService.tsx
frontend/src/components/Users/UsersList/index.tsx
frontend/src/components/Users/UsersList/partials/ListOfCards/index.tsx
frontend/src/hooks/useUser.tsx
frontend/src/pages/users/index.tsx

https://github.com/xgeekshq/split/issues/594
Relates to https://github.com/xgeekshq/split/issues/602
Screenshots (if visual changes)
Proposed Changes
-A lazy loading strategy should be implemented to avoid fetching all the platform users at the same time. So the user can fetch, for example, 15 at a time and more 15 when the scroll reaches its end.
@GuiSanto
This pull request closes https://github.com/xgeekshq/split/issues/602

feat: users lazy loading scroll

---

backend/src/modules/queue/queue.module.ts
frontend/src/components/Board/Column/Column.tsx
frontend/src/components/Board/Column/styles.tsx
frontend/src/components/Board/DragDropArea/index.tsx
frontend/src/components/CardBoard/CardBody/CardBody.tsx
frontend/src/helper/board/transformBoard.tsx
frontend/src/hooks/useBoard.tsx
frontend/src/pages/boards/[boardId].tsx
frontend/src/store/board/atoms/board.atom.tsx
frontend/src/store/board/atoms/filterColumns.tsx
frontend/src/store/board/selectors/get-board.selector.tsx
frontend/src/styles/globals.tsx
frontend/src/styles/pages/boards/board.styles.tsx
frontend/src/types/card/updateCardPosition.dto.ts

Fixes #703
- Remove the dragged card correctly when the columns are sorted
- Expand the scroll behaviour to the whole board page
This pull request closes #703

fix: scroll in a board and drag and drop cards when the columns are sorted

---

backend/src/libs/dto/param/pagination.params.ts
backend/src/modules/users/applications/get.user.application.ts
backend/src/modules/users/controller/users.controller.ts
backend/src/modules/users/interfaces/applications/get.user.application.interface.ts
backend/src/modules/users/interfaces/services/get.user.service.interface.ts
backend/src/modules/users/repository/user.repository.interface.ts
backend/src/modules/users/repository/user.repository.ts
backend/src/modules/users/services/get.user.service.ts

- backend receives a filter that will return users that contain that string in the firstname, lastname and email
This pull request closes #601

feat: backend done for search user

---

frontend/src/components/Users/UserEdit/index.tsx
frontend/src/components/Users/UserEdit/partials/ListOfCards/index.tsx
frontend/src/components/Users/UserEdit/partials/UserHeader/index.tsx
frontend/src/components/Users/UserEdit/partials/UserHeader/styles.tsx
frontend/src/components/Users/UsersList/partials/CardUser/CardBody.tsx
frontend/src/components/Users/UsersList/partials/ListOfCards/index.tsx
frontend/src/pages/users/[userId].tsx
frontend/src/styles/stitches/partials/colors/primary.colors.ts

#712 
- As a Super Admin, in the top left of the page, I want to see which User I am editing and, in case I am editing a Super Admin, have a "SUPER ADMIN" banner next to its name.
- In addition, I want to see a button in the top right that says "Add user to new team".
@GuiSanto 
This pull request closes #712

feat: top layout for users edit page

---

backend/src/libs/dto/param/user.teams.param.ts
backend/src/modules/teams/controller/team.controller.ts

- refactored the backend of "get teams of user" in order to work with any user. Previously the controller only received the ID from the session.
This pull request closes #715 #717

feat: get teams of user backend refactored

---

frontend/src/api/teamService.tsx
frontend/src/components/Teams/CreateTeam/CardEnd/RoleDescription.tsx
frontend/src/components/Teams/TeamsList/partials/CardTeam/CardBody.tsx
frontend/src/components/Users/UserEdit/index.tsx
frontend/src/components/Users/UserEdit/partials/ListOfCards/index.tsx
frontend/src/components/Users/UserEdit/partials/UserHeader/index.tsx
frontend/src/components/Users/UsersList/partials/CardUser/CardBody.tsx
frontend/src/components/Users/UsersList/partials/CardUser/EditUser.tsx
frontend/src/pages/users/[userId].tsx

- Showing all teams that a user is part of
- Delete team of a user is also done, because we used the existing component of Teams.
- Page auto-refreshes when a user is deleted
This pull request closes #715 #717

feat: displaying all teams of user. Delete team of user too

---

frontend/src/components/Teams/CreateTeam/CardMember/RoleSettings.tsx
frontend/src/components/Teams/CreateTeam/CardMember/index.tsx
frontend/src/components/Teams/CreateTeam/index.tsx
frontend/src/components/Teams/TeamsList/partials/CardTeam/DeleteTeam.tsx
frontend/src/hooks/useTeam.tsx
frontend/src/types/team/useTeam.ts

#716 
- As a Super Admin, I want to change the role that a user has on a team. The options available should be: Team Member, Team Admin and Stakeholder.
@GuiSanto 
This pull request closes #716

feat: edit role of user of corresponding team when editing user

---

frontend/src/components/Users/UserEdit/partials/TeamsDialog/SearchInput.tsx
frontend/src/components/Users/UserEdit/partials/TeamsDialog/index.tsx
frontend/src/components/Users/UserEdit/partials/TeamsDialog/styles.tsx
frontend/src/components/Users/UserEdit/partials/UserHeader/index.tsx

#747
- As a Super Admin, I want to click on a button called "Add user to new team" and see a layout pop-up on the side with the list of Teams that user is not yet part of.
- In the top-left, it must say "Add new team" and on the top-right an "X" icon, to close the pop-up.
- Below it, must be a search box, with a magnifying glass icon and a "Search team" placeholder.
- In the middle, must say "Team", followed by the list of teams that user is not a member of. The list must only have 1 column.
- In the bottom, there should be 2 buttons: Cancel and Add, both should close the pop-up.
This pull request closes #747

feat: layout complete

---

frontend/src/components/CreateBoard/SplitBoard/SubTeamsTab/SelectTeam/index.tsx
frontend/src/pages/boards/newSplitBoard.tsx

Fixes #745 
- New board shows team on 1st render when user clicks on "Create first team board" of a team.
This pull request closes #745

fix: new board shows team selected on 1st render

---

backend/src/modules/teams/applications/get.team.application.ts
backend/src/modules/teams/controller/team.controller.ts
backend/src/modules/teams/interfaces/applications/get.team.application.interface.ts
backend/src/modules/teams/interfaces/services/get.team.service.interface.ts
backend/src/modules/teams/services/get.team.service.ts

-  I should get a list of all teams a user does not belong to, so I can choose which ones to add him to.
This pull request closes #748

feat: get teams the user is not part of

---

backend/src/modules/teams/applications/update.team.application.ts
backend/src/modules/teams/controller/team.controller.ts
backend/src/modules/teams/interfaces/applications/update.team.application.interface.ts
backend/src/modules/teams/interfaces/services/update.team.service.interface.ts

Issue #749
- receive a TeamUser DTO and create document/s on that Mongo collection
This pull request closes ##749

feat: add teams to user (create teamuser db documents)

---

frontend/src/components/Teams/CreateTeam/CardMember/RoleSettings.tsx
frontend/src/components/Teams/TeamsList/partials/CardTeam/CardBody.tsx
frontend/src/components/Users/UserEdit/partials/ListOfCards/index.tsx

Fixes #757
- when editing the role of a user on a team, it now works for everyone on the list
This pull request closes #757

fix: user edit role working

---

backend/src/libs/dto/param/pagination.params.ts
backend/src/modules/boards/applications/get.board.application.ts
backend/src/modules/boards/controller/boards.controller.ts
backend/src/modules/boards/interfaces/applications/get.board.application.interface.ts
backend/src/modules/boards/interfaces/findQuery.ts
backend/src/modules/boards/interfaces/services/get.board.service.interface.ts
backend/src/modules/boards/services/get.board.service.ts
frontend/src/api/boardService.tsx
frontend/src/components/Teams/CreateTeam/CardMember/RoleSettings.tsx

Relates to #756
- Filter boards by team endpoint (with pagination)
This pull request closes #756

feat: filter boards by team endpoint

---

frontend/src/components/Users/UsersList/partials/ListOfCards/index.tsx

Fixes #766
- debounce mechanism changed from 100ms to 300ms to avoid spam of requests
This pull request closes #766

fix: debounce increased from 100ms to 300ms

---

frontend/src/components/CreateBoard/Configurations/BoardConfigurations.tsx
frontend/src/components/CreateBoard/RegularBoard/ParticipantsTab/ListParticipants/index.tsx
frontend/src/components/CreateBoard/RegularBoard/ParticipantsTab/SelectParticipants/index.tsx
frontend/src/components/CreateBoard/RegularBoard/SettingsTabs/index.tsx
frontend/src/components/Teams/CreateTeam/ListCardsMembers/index.tsx
frontend/src/components/Teams/CreateTeam/ListMembers/index.tsx
frontend/src/components/Teams/CreateTeam/ListMembersDialog/index.tsx
frontend/src/pages/boards/newRegularBoard.tsx
frontend/src/pages/teams/[teamId].tsx
frontend/src/pages/teams/new.tsx

Relates to #679 
- Add configuration tab with "Make board public" switch on the frontend
-List members dialog shows users sorted by checked
- Fix team users page (remove duplicated add members button)
This pull request closes #679

feat: configurations tab

---

frontend/src/components/Teams/CreateTeam/CardMember/RoleSettings.tsx
frontend/src/components/Teams/CreateTeam/CardMember/index.tsx
frontend/src/components/Teams/Team/CardEnd/index.tsx
frontend/src/components/Teams/Team/ListCardMembers/index.tsx
frontend/src/hooks/useTeam.tsx

#782 and #781
Fixes #782 and #781
- Only users with privileges (isSAdmin, stakeholder, team admin) can change the roles of teams. Members are not allowed.
- Remove button "add/remove member" when is team member.
- Change Popup message when adding teams to user.
@GuiSanto 
This pull request closes #781 and #782

fix: multiple bugs

---

frontend/src/components/Board/Settings/index.tsx

Fixes #780
- clicking on the magic wand generates a new Responsible
- the code was correct, but the initial if statement was doing the opposite of what it should
This pull request closes #780

fix: random responsible generator fixed

---

backend/src/modules/comments/controller/comments.controller.ts
backend/src/modules/comments/interfaces/applications/delete.comment.application.interface.ts
backend/src/modules/comments/interfaces/services/delete.comment.service.interface.ts
backend/src/modules/comments/schemas/comment.schema.ts
backend/src/modules/comments/services/create.comment.service.ts
backend/src/modules/comments/services/delete.comment.service.ts
frontend/src/components/Board/Card/CardBoard.tsx
frontend/src/components/Board/Card/CardFooter.tsx
frontend/src/helper/board/transformBoard.tsx
frontend/src/hooks/useComments.tsx
frontend/src/pages/boards/[boardId].tsx
frontend/src/types/comment/comment.ts

Fixes #803
- Sort comments by creation date
- Create anonymous comments in a card group
- Comment deletion is now possible
This pull request closes #803

fix: comment sort by date, create anonymous comments in card group

---

backend/src/modules/boards/services/create.board.service.ts
backend/src/modules/schedules/services/create.schedules.service.ts
backend/src/modules/teams/repositories/team-user.repository.ts
backend/src/modules/teams/repositories/team.repository.ts
frontend/src/components/Boards/MyBoards/index.tsx
frontend/src/hooks/useBoard.tsx
frontend/src/hooks/useCreateBoard.tsx
frontend/src/hooks/useSocketIO.ts
frontend/src/pages/teams/new.tsx

Fixes #806
Fix:
- New joiners should not be marked as responsible on board creation
- Check new joiners status when creating a team
- Team creator should not be new joiner
- Delete board: delay on updating boardsList
This pull request closes #806

fix: fix newJoiner status, responsible of subBoard

---

backend/src/modules/communication/applications/slack-communication.application.ts
frontend/src/components/Board/Column/Column.tsx
frontend/src/components/Primitives/TextArea.tsx
frontend/src/pages/boards/[boardId].tsx

Fixes #776
- Hide board settings when it's closed so the on press enter key observer that is present on that component is not triggered. Now all users can add a new line on the text area
- Increase text area height based on the content length
- When the card or comment is edited it now appears with the height based on the content
This pull request closes  #776

fix: text area new line and height

---

backend/src/modules/cards/controller/cards.controller.ts
backend/src/modules/cards/dto/update-position.card..dto.ts
backend/src/modules/socket/gateway/socket.gateway.ts
backend/src/modules/teams/repositories/team.repository.ts
backend/src/modules/votes/controller/votes.controller.ts
backend/src/modules/votes/dto/vote.dto.ts
backend/src/modules/votes/services/create.vote.service.ts
frontend/src/components/Board/Card/CardBoard.tsx
frontend/src/components/Board/Card/CardFooter.tsx
frontend/src/components/Board/Card/CardItem/CardItem.tsx
frontend/src/helper/board/transformBoard.tsx
frontend/src/hooks/useCards.tsx
frontend/src/hooks/useSocketIO.ts
frontend/src/hooks/useVotes.tsx
frontend/src/types/vote/vote.dto.ts

Fixes #825 
Note: this should solve the majority of issues regarding performance when many people are moving or voting the cards in real-time. This should be tested in the live version
- When voting in a card or moving its position now a socket message is sent to all users that are seeing the board and receiving that they will update the board locally instead of making a board request 
- If some error occurs in the backend during these updates a message is sent to all users to refetch the board. (this may not be necessary)
This pull request closes #825

fix: update card position and votes with sockets

---

backend/src/infrastructure/config/configuration.ts
backend/src/modules/boards/services/get.board.service.ts
backend/src/modules/boards/utils/populate-board.ts
backend/src/modules/cards/services/create.card.service.ts
backend/src/modules/cards/services/delete.card.service.ts
backend/src/modules/cards/services/merge.card.service.ts
backend/src/modules/cards/services/unmerge.card.service.ts
backend/src/modules/cards/services/update.card.service.ts
backend/src/modules/cards/shared/push.card.ts
backend/src/modules/comments/applications/update.comment.application.ts
backend/src/modules/comments/controller/comments.controller.ts
backend/src/modules/comments/dto/update.comment.dto.ts
backend/src/modules/comments/interfaces/applications/update.comment.application.interface.ts
backend/src/modules/comments/interfaces/services/update.comment.service.interface.ts
backend/src/modules/comments/services/create.comment.service.ts
backend/src/modules/comments/services/delete.comment.service.ts
backend/src/modules/comments/services/update.comment.service.ts
backend/src/modules/schedules/services/create.schedules.service.ts
frontend/.eslintrc.json
frontend/src/components/Board/AddCardOrComment.tsx
frontend/src/components/Board/Card/CardBoard.tsx
frontend/src/components/Board/Card/CardFooter.tsx
frontend/src/components/Board/Card/CardItem/CardItem.tsx
frontend/src/components/Board/Column/Column.tsx
frontend/src/components/Board/Comment/Comment.tsx
frontend/src/components/Board/Comment/Comments.tsx
frontend/src/helper/board/transformBoard.tsx
frontend/src/hooks/useCards.tsx
frontend/src/hooks/useComments.tsx
frontend/src/types/comment/updateComment.dto.ts

Fixes #835 
- Unmerge is now available to everyone 
- Try to handle some crashes
- Reduce the board requests on success
This pull request closes #835

fix: unmerge, avoid requesting on success, handle erros

---

backend/src/modules/boards/services/create.board.service.ts
backend/src/modules/teams/repositories/team-user.repository.ts
frontend/src/utils/verifyIfIsNewJoiner.ts

Fixes #842 
- Fixed verifyIsNewJoiner backend function.
This pull request closes #842

fix: verifyNewJoiner function in backend

---

frontend/src/components/Board/Card/CardFooter.tsx
frontend/src/hooks/useVotes.tsx

- Add votes optimistic update on mutate

fix: votes

---

backend/src/modules/boards/services/get.board.service.ts
backend/src/modules/teams/repositories/team.repository.ts
backend/src/modules/teams/services/get.team.service.ts
frontend/src/components/Board/Header/index.tsx
frontend/src/components/CardBoard/CardBody/CardBody.tsx
frontend/src/components/CardBoard/CardBody/CardTitle.tsx
frontend/src/components/CardBoard/CardBody/CardTitle/partials/Title/styles.tsx
frontend/src/components/Teams/TeamsList/partials/CardTeam/CardBody.tsx
frontend/src/pages/boards/[boardId].tsx
frontend/src/pages/dashboard/index.tsx

Fixes #846 
- Fix superAdmin/ stakeholder access to the boards
- Fix breadCrumbs when an user interacts with a board
- Fix board count on the teams page
- Remove mainBoardData object from response when a board is fetched
This pull request closes #846

fix: board loading

---

backend/src/modules/teams/repositories/team.repository.ts
backend/src/modules/teams/services/get.team.service.ts

Relates to #845
Fixes #845
- The list of team members is ordered alphabetically
This pull request closes #845

fix: team page member sort

---

frontend/src/components/Boards/Filters/FilterBoards.tsx
frontend/src/components/Boards/Filters/FilterSelect.tsx
frontend/src/components/Boards/Filters/styles.tsx

Relates to #869 
Fixes #869 
- Filters now have a White Background, as shown in the design documents
- Dropdown options cursor is now a pointer.
- Dropdown "menu" has a 12px rounded border
- Dropdown options selected and hover background color fixed
This pull request closes #869

fix: bug drop down design

---

frontend/src/components/Teams/CreateTeam/ListCardsMembers/index.tsx
frontend/src/components/Teams/CreateTeam/TipBar/index.tsx

Relates to #877 
Fixes #877 
- Fixed the Margins on the New Team page
- New Joiner text is displayed all the time
This pull request closes #877

fix: 877 bug create new team page design

---

frontend/src/components/Teams/TeamsList/partials/CardTeam/CardBody.tsx
frontend/src/components/Teams/TeamsList/partials/ListOfCards/index.tsx
frontend/src/components/Users/UserEdit/partials/ListOfCards/index.tsx

Relates to #883
Fixes #883 
- Fixed Gap between Team-Rows
This pull request closes #883

fix: gap between team-rows

---

frontend/src/components/Primitives/Input.tsx
frontend/src/components/auth/LoginForm/index.tsx
frontend/src/components/auth/SignUp/SignUpForm.tsx
frontend/src/pages/api/auth/[...nextauth].tsx
frontend/src/pages/index.tsx

Relates to #890 
Fixes #890
- When logging in with invalid credentials we get the proper error message
- The Image has a Shadow
- The Password Input a dark gray icon
This pull request closes #890

fix: bug login page design and bugs

---

frontend/src/components/CreateBoard/Select/index.tsx
frontend/src/components/CreateBoard/SplitBoard/SubTeamsTab/SelectTeam/index.tsx

Relates to #895 
Fixes #895 
- Any user will only see the teams he is a team-admin or stakeholder. And no longer be able to select a team he can't create a board for.
- If the user doesn't have any teams he can create boards for, it displays the error message.
This pull request closes #895

fix: new split board team selection

---

frontend/src/components/Board/Column/Column.tsx

Relates to #901 
Fixes #901 
- Changed Background color of the card amount "badge"
This pull request closes #901

fix: card amount background color

---

frontend/src/components/Board/Column/partials/SortMenu/styles.tsx
frontend/src/components/Primitives/Popover.tsx

Relates to #899 
Fixes #899 
- Fix the settings and sorting popup options background color
This pull request closes #899

fix: card settings background color

---

frontend/src/components/Board/AddCardOrComment.tsx
frontend/src/pages/boards/[boardId].tsx

Relates to #902 
Fixes #902 
- Both texts with font weight of medium just like in the figma designs 
This pull request closes #902

fix: font weight board settings and add new card buttons

---

frontend/src/components/CreateBoard/SplitBoard/SubTeamsTab/MainBoardCard.tsx
frontend/src/components/Primitives/Checkbox.tsx
frontend/src/hooks/useCreateBoard.tsx
frontend/src/pages/boards/newSplitBoard.tsx

Relates to #909 
Fixes #909 
- Store the "Create Slack group for each sub-team" checkbox state when the user changes the tab in the split board creation page
This pull request closes #909

fix: store state on create slack group checkbox

---

frontend/src/components/CardBoard/CardBody/CardTitle.tsx
frontend/src/components/CardBoard/CardBody/CardTitle/index.tsx
frontend/src/components/CreateBoard/TipBar.tsx
frontend/src/pages/boards/newSplitBoard.tsx

Relates to #914  
Fixes #914 
- Found and replaced 4 occurrences of "splitted", changed them to "split"
This pull request closes #914

fix: split instead of splitted

---

frontend/src/components/Board/Settings/styles.tsx
frontend/src/components/Boards/MyBoards/ListBoardMembers/styles.tsx
frontend/src/components/CreateBoard/TipBar.tsx
frontend/src/styles/pages/boards/newSplitBoard.styles.tsx

Relates to #917
Fixes #917
- Fix double scrollbar on create new board pages
- Fix double scrollbar on board members list dialog
This pull request closes #917

fix: new split board page scroll

---

backend/src/libs/constants/database.ts
backend/src/modules/boards/interfaces/services/get.board.service.interface.ts
backend/src/modules/boards/services/create.board.service.ts
backend/src/modules/boards/services/get.board.service.ts
backend/src/modules/votes/services/create.vote.service.ts
backend/src/modules/votes/services/delete.vote.service.ts
frontend/src/helper/board/transformBoard.tsx
frontend/src/hooks/useCards.tsx
frontend/src/hooks/useComments.tsx
frontend/src/hooks/useSocketIO.ts
frontend/src/hooks/useVotes.tsx
frontend/src/store/operations/atom/operations-queue.atom.ts

Fixes #912
- wait for the board users creation before sending the slack message
- simple queue implementation to save board operations that comes from the socket
- lock board updates if some transformation is happening
Note: this queue system works well locally with two users but it needs a test with more users
This pull request closes #912

fix: slack participants and votes

---

frontend/src/components/Primitives/Checkbox.tsx

Relates to #924
Fixes #924 
- Verify checkbox id to check if it's being used to enable slack in creating a board because it's preventing the user from creating teams with members.
This pull request closes #924

fix: verify checkbox id

---

frontend/src/components/Boards/MyBoards/ListBoards/index.tsx
frontend/src/components/Teams/CreateTeam/CardMember/index.tsx
frontend/src/components/Teams/Team/ListCardMembers/index.tsx
frontend/src/components/Teams/TeamsList/partials/CardTeam/CardBody.tsx
frontend/src/components/Teams/TeamsList/partials/ListOfCards/index.tsx
frontend/src/components/Users/UsersList/partials/CardUser/CardBody.tsx
frontend/src/components/Users/UsersList/partials/ListOfCards/index.tsx

Relates to #926 
Fixes #926 
- Fixed the Scrollable Lists Margins going off the screen
This pull request closes #926

fix: scrollable containers margins

---

frontend/src/components/CreateBoard/Select/index.tsx
frontend/src/pages/boards/newSplitBoard.tsx

Relates to #928 
Fixes #928 
- Add the create team to the no teams alert
- Change select background color when disabled
This pull request closes #928

fix: add alert button and disabled select color

---

frontend/src/components/Primitives/Checkbox.tsx

Relates to #934 
Fixes #934 
- Set check value only on slackEnable (so it is persistent when changing tabs when creating a board but doesn't affect the behaviour of the checkbox on other components)
This pull request closes #934

fix: set check value only on slackEnable

---

backend/src/modules/azure/services/auth.azure.service.ts

- Use email or the unique name to add a user to the slack main channel

fix: use unique name or email to add a user into slack main channel

---

frontend/src/components/Board/Card/PopoverSettings.tsx
frontend/src/components/Board/Column/partials/OptionsMenu/index.tsx

Fixes #967 
- When the modal to eliminate the card is open, the popover closes
This pull request closes #967

fix: close popover when modal is opened

---

frontend/src/components/CardBoard/CardBody/CardEnd.tsx

Fixes  #977 
- In the dashboard, the sub-board card now shows the sub-team name and the board members
This pull request closes #977

fix: participants

---

backend/src/modules/boards/boards.module.ts
backend/src/modules/boards/controller/boards.controller.spec.ts
backend/src/modules/boards/controller/boards.controller.ts
backend/src/modules/boards/dto/update-board.dto.ts
backend/src/modules/boards/services/create.board.service.ts
backend/src/modules/boards/services/update.board.service.ts
frontend/src/api/boardService.tsx
frontend/src/components/Board/RegularBoard/index.tsx
frontend/src/components/Board/Settings/index.tsx
frontend/src/components/Board/Settings/partials/Columns/DeleteButton.tsx
frontend/src/store/board/atoms/board.atom.tsx
frontend/src/types/board/useBoard.ts

Relates to #958 
- Fixed problem with votes count of a board user.
- Deleting columns returns votes from the deleted cards.
@patricia-mdias

feat: delete board columns/handle votes

---

frontend/src/components/Boards/MyBoards/ListBoardMembers/index.tsx

Relates to #990
Fixes #990
- Board Members now show Team Admins and Stakeholders first in case of a SPLIT Board.
- In case of a Regular Board, it displays the Board Creator or Responsible first.
- Then it shows all the Team Members
This pull request closes #990

fix: order board members

---

CHANGELOG.md
backend/package.json
backend/src/modules/boards/boards.module.ts
backend/src/modules/boards/controller/boards.controller.spec.ts
backend/src/modules/boards/controller/boards.controller.ts
backend/src/modules/boards/dto/update-board.dto.ts
backend/src/modules/boards/services/create.board.service.ts
backend/src/modules/boards/services/update.board.service.ts
backend/src/modules/communication/applications/slack-communication.application.ts
backend/src/modules/communication/applications/slack-merge-board.application.ts
backend/src/modules/communication/applications/slack-responsible.application.ts
frontend/package.json
frontend/src/api/boardService.tsx
frontend/src/components/Board/RegularBoard/index.tsx
frontend/src/components/Board/Settings/index.tsx
frontend/src/components/Board/Settings/partials/Columns/DeleteButton.tsx
frontend/src/helper/board/transformBoard.tsx
frontend/src/pages/boards/[boardId].tsx
frontend/src/pages/boards/newRegularBoard.tsx
frontend/src/store/board/atoms/board.atom.tsx
frontend/src/types/board/useBoard.ts
package.json

Fixes #975 
- Regular Board votes fixed.
- Regular Board deleting card from merged group of cards.
- When creating a regular board, maxVotes is undefined (when not onFocus)
- Deleted one UseEffect causing error on the console, reusing another one.
- Fix handle votes when the card deleted belonged to the user on index 0
@patricia-mdias 
This pull request closes #975

fix: regular board votes and quick create

---

frontend/src/components/Board/Settings/partials/Columns/ColumnBoxAndDelete.tsx
frontend/src/components/Primitives/Input.tsx

Relates to #1009
Fixes #1009
- Adding a column doesn't discard the changes on previous edited columns.
This pull request closes #1009

fix: adding a column doesn't affect previous edited columns

---

backend/src/modules/boards/services/update.board.service.ts
frontend/src/api/boardService.tsx
frontend/src/components/Board/Column/Column.tsx
frontend/src/components/Board/Column/partials/AlertDeleteAllCards/index.tsx
frontend/src/components/Board/Column/partials/AlertDeleteColumn/index.tsx
frontend/src/components/Board/Column/partials/OptionsMenu/index.tsx
frontend/src/components/Board/Column/partials/UpdateColumnDialog/index.tsx
frontend/src/components/Board/Settings/index.tsx
frontend/src/hooks/useColumn.tsx
frontend/src/types/column.ts

Relates to #958 
Relates to #738 
On a regular board, a user with permitions can:
- Empty cards from column
- Delete column
- Console error fixed
This pull request closes #958 
This pull request closes #738

feat: delete column/cards on a board

---

frontend/src/components/Board/Card/CardBoard.tsx
frontend/src/components/Board/Card/CardItem/CardItem.tsx
frontend/src/components/Board/Column/styles.tsx
frontend/src/components/Board/Comment/Comment.tsx
frontend/src/components/Board/Comment/Comments.tsx

Relates to #963 
Fixes #963
- For "regular users" Disabled:
- Card drag on the main board
- Card edit on the main board
- Adding new comments on the main board
- Editing existing comments on the main board
This pull request closes #963

fix: disable card drag on mainboard

---

backend/src/libs/utils/hideText.ts
backend/src/modules/boards/dto/board.dto.ts
backend/src/modules/boards/interfaces/services/create.board.service.interface.ts
backend/src/modules/boards/schemas/board.schema.ts
backend/src/modules/boards/services/create.board.service.ts
backend/src/modules/boards/services/update.board.service.ts
backend/src/modules/schedules/services/create.schedules.service.ts
frontend/src/components/Board/AddCardOrComment.tsx
frontend/src/components/Board/Card/CardBoard.tsx
frontend/src/components/Board/Card/CardItem/CardItem.tsx
frontend/src/components/Board/Card/CardItem/CardItemList.tsx
frontend/src/components/Board/Column/CardsList.tsx
frontend/src/components/Board/Column/Column.tsx
frontend/src/components/Board/Column/partials/AlertDeleteColumn/index.tsx
frontend/src/components/Board/Comment/Comment.tsx
frontend/src/components/Board/Comment/Comments.tsx
frontend/src/components/Board/DragDropArea/index.tsx
frontend/src/components/Board/Settings/index.tsx
frontend/src/components/CreateBoard/Configurations/BoardConfigurations.tsx
frontend/src/components/Primitives/Checkbox.tsx
frontend/src/helper/board/blurFilter.ts
frontend/src/hooks/useCreateBoard.tsx
frontend/src/pages/boards/newRegularBoard.tsx
frontend/src/pages/boards/newSplitBoard.tsx
frontend/src/store/createBoard/atoms/create-board.atom.tsx
frontend/src/types/board/board.ts
frontend/src/types/column.ts

Fixes #1021
Fixes #989 
- Add translate3D to force the hardware acceleration when using blur
- Add option to post anonymously by default
- Refactor the replace text method
- Setting hide cards in a sub-board by default
- Fix selecting the text in the text area of a card with firefox
This pull request closes #1021 and closes #989

fix: blur, hide cards, hide text, post anonymously

---

frontend/src/components/Board/AddCardOrComment.tsx
frontend/src/components/Board/Column/partials/UpdateColumnDialog/index.tsx
frontend/src/components/Primitives/TextArea.tsx
frontend/src/stories/TextArea.stories.tsx

Relates to #1039
Fixes #1039 
- TextArea primitive refactor
- Add TextArea primitive to storybook
This pull request closes #1039

feat: textarea primitive story

---

frontend/src/components/auth/LoginForm/index.tsx

Relates to #1035 
Fixes #1035 
- Added a onChange handler to the Email / Password Inputs to set the Form Value.
- The problem was that the react-form-hooks only sets the input value onBlur.
This pull request closes #1035

fix: input onChange handler

---

backend/src/modules/boards/utils/clean-board.ts
backend/src/modules/cards/dto/card.item.dto.ts
backend/src/modules/comments/services/update.comment.service.ts
backend/src/modules/communication/applications/slack-merge-board.application.ts
frontend/src/components/Board/Card/CardItem/CardItem.tsx
frontend/src/components/Board/Column/Column.tsx
frontend/src/components/Board/Comment/Comment.tsx
frontend/src/helper/board/countCards.ts
frontend/src/hooks/useCards.tsx

- fix update comment by responsible
- fix count cards

fix: update comments as responsible

---

frontend/package-lock.json
frontend/src/components/RecoilDevTools/RecoilDevTools.tsx
frontend/src/pages/_app.tsx
frontend/src/utils/constants.ts
package-lock.json

Relates to #1060 
Fixes #1060
<div align="center">
</div>
- Added a new Button that Dumps the current Recoil State to the console.
- This Button:
- Is controlled by a Flag inside the `constants.tsx` file
- Is always on top of the Page in the Bottom Left Corner
This pull request closes #1060

feat: basic recoil dev tools

---

frontend/src/components/Board/RegularBoard/ParticipantsList/ParticipantCard.tsx/index.tsx
frontend/src/components/Board/RegularBoard/ParticipantsList/ParticipantsLayout.tsx
frontend/src/components/Board/RegularBoard/ParticipantsList/index.tsx
frontend/src/components/Board/RegularBoard/ReagularHeader/HeaderParticipants.tsx
frontend/src/components/Board/RegularBoard/ReagularHeader/index.tsx
frontend/src/components/Board/RegularBoard/index.tsx

Relates to #1038 
Fixes #1031 
- Board Responsible view
- Super admin view
- Regular Board Participant
- Add toggle to edit responsibles of a Regular board.
- Show ad/remove participants and responsible toggle when user has permissions.
This pull request closes #1031

feat: regular board no team edit responsible

---

frontend/src/store/operations/atom/operations-queue.atom.ts
frontend/src/store/vote/atoms/vote.atom.tsx

Fixes #1079 
- Fix duplicated key name of atoms ('usersWithTeams') used on 3 atoms.
This pull request closes #1079

fix: renamed keys of atoms

---

frontend/src/pages/boards/[boardId].tsx
frontend/src/pages/boards/[boardId]/participants.tsx

Fixes #1084 
- Show responsibles first on the participants list (participants page)
This pull request closes #1084

fix: participants list ordered by responsibles>member

---

frontend/src/components/Board/AddCardOrComment.tsx
frontend/src/components/Board/Card/CardBoard.tsx
frontend/src/components/Board/Card/CardItem/CardItem.tsx
frontend/src/components/Board/Card/CardItem/CardItemList.tsx
frontend/src/components/Board/Column/CardsList.tsx
frontend/src/components/Board/Column/Column.tsx
frontend/src/components/Board/DragDropArea/index.tsx
frontend/src/helper/board/defaultColumns.ts
frontend/src/types/board/board.ts
frontend/src/utils/constants.ts

Fixes #1090 
- When editing a card, the textarea value is the text of the card and not the placeholder (previous behavior)
- On a regular board, when the "default card text" is active, the placeholder also acts as value for the textarea
- Fix toggle when user toggles the default car text button
- Add team to UpdateBoardType's schema and pass team id field when updating a column position
This pull request closes #1090

fix: placeholder replaces card

---

frontend/src/components/Board/AddCardOrComment.tsx
frontend/src/components/Primitives/TextArea.tsx

Relates to #1096
Fixes #1096 
- Let the textarea primitive component decide for itself whether it has a state of error, valid or default based on the information provided by its form.
This pull request closes #1096

fix: textarea validation state

---

frontend/src/components/Board/Column/styles.tsx
frontend/src/components/Board/DragDropArea/index.tsx
frontend/src/components/Primitives/AlertBox/index.tsx
frontend/src/components/Primitives/AlertBox/styles.tsx
frontend/src/stories/AlertBox.stories.tsx

Relates to #1112 
Fixes #1112
- Add a gap between board columns so the alert box is aligned on the left side. How it was before:
Now:
- Add the AlertBox primitive to Storybook
This pull request closes #1112

feat: alert box primitive story

---

frontend/src/components/Board/DragDropArea/index.tsx

Relates to #1114 
Fixes #1114 
- Fix board page limited scroll
- Add margin bottom to the drag and drop area in the board page
This pull request closes #1114

fix: fix board page scroll and add margin bottom

---

frontend/src/components/Board/Card/CardFooter.tsx

Fixes #1102
- Disable comments button only if the cards are hidden and the cards don't belong to the logged user
This pull request closes #1102

fix: add comment on own cards if they are hidden

---

frontend/src/components/icons/Sprite.tsx
frontend/src/stories/Icons.stories.tsx
frontend/src/stories/components/Card.tsx

Relates to #1111 
Fixes #1111 
- List all items with names
- Searchable Icons in Storybook
This pull request closes #1111

feat: icons with search

---

frontend/src/components/CreateBoard/RegularBoard/ParticipantsTab/RadioGroupParticipants/index.tsx
frontend/src/components/CreateBoard/RegularBoard/ParticipantsTab/SelectParticipants/index.tsx
frontend/src/components/CreateBoard/RegularBoard/ParticipantsTab/index.tsx
frontend/src/components/CreateBoard/RegularBoard/SettingsTabs/index.tsx

Fixes #1098
- The selected participants aren't discarded if the user changes the tab in a regular board creation
This pull request closes #1098

fix: regular board change tab

---

backend/src/modules/auth/auth.module.ts
backend/src/modules/auth/services/register.auth.service.ts
backend/src/modules/boards/services/get.board.service.ts
backend/src/modules/boards/utils/populate-board.ts
backend/src/modules/users/dto/guest.user.dto.ts
frontend/src/components/Board/RegularBoard/ParticipantsList/ParticipantCard.tsx/index.tsx
frontend/src/components/Board/RegularBoard/ParticipantsList/index.tsx
frontend/src/components/Board/RegularBoard/ReagularHeader/HeaderParticipants.tsx
frontend/src/components/Board/RegularBoard/ReagularHeader/index.tsx
frontend/src/components/Board/Settings/partials/ConfigurationSettings/ConfigurationSwitch.tsx
frontend/src/components/Teams/CreateTeam/ListMembersDialog/index.tsx
frontend/src/pages/boards/[boardId]/participants.tsx
frontend/src/types/user/user.ts

Related to #1120
Related to #742 
- Regular Board with team, displays participants on the participants page.
- Avoided removing the only board responsible.
@CatiaAntunes96 
This pull request closes #1120 
This pull request closes #742

refactor: team participants page

---

backend/src/modules/boards/services/get.board.service.ts

Fixes #1152 
- Get all boards as a super admin returns boards with pagination.
This pull request closes #1152

fix: endpoint returns paginated boards to sAdmin

---

backend/src/modules/boards/controller/boards.controller.ts

Relates to #1139 
- Fix description when code 200
- Add example value schema
- Add Unauthorized 
This pull request closes #1139

refactor: enhance swagger on updateBoardPhase

---

frontend/src/components/Board/AddCardOrComment.tsx

Relates to #1207 
Fixes #1207 
- Changed the Flex property to have the components justified between
- Fixed the Buttons position when the checkbox is not present
This pull request closes #1207

fix: checkbox position

---

backend/src/libs/guards/getBoardPermissions.guard.ts
backend/src/libs/test-utils/mocks/factories/board-factory.mock.ts
backend/src/libs/test-utils/mocks/factories/boardUser-factory.mock.ts
backend/src/libs/test-utils/mocks/factories/card-factory.mock.ts
backend/src/libs/test-utils/mocks/factories/dto/userDto-factory.ts
backend/src/libs/test-utils/mocks/factories/team-factory.mock.ts
backend/src/libs/test-utils/mocks/factories/teamUser-factory.mock.ts
backend/src/libs/test-utils/mocks/factories/user-factory.ts
backend/src/modules/boards/interfaces/services/get.board.service.interface.ts
backend/src/modules/boards/repositories/board-user.repository.interface.ts
backend/src/modules/boards/repositories/board-user.repository.ts
backend/src/modules/boards/services/get.board.service.spec.ts
backend/src/modules/boards/services/get.board.service.ts

Relates to:
- #1215 
- Add tests to test get board service
-  Refactor of query from boardUser repository
- Add boardUser, team, teamUser, user and UserDto factories
- #1215

test: add tests to get board service

---

frontend/src/components/Primitives/Dialogs/Dialog/DialogFooter.tsx
frontend/src/pages/boards/newRegularBoard.tsx

Relates to:
- #1243 
Fixes:
- #1243 
- The save button of the board settings dialog is not appearing
- The cards of the create regular board page are not vertically aligned
- #1243

fix: board settings save button and create regular board cards

---

frontend/src/components/Primitives/Alerts/ConfirmationDialog/ConfirmationDialog.tsx

Relates to:
- #1246 
Fixes:
- #1246 
- Confirmation Dialog cancel button has primaryOutline variation
- #1246

fix: cancel button color

---

backend/src/modules/communication/applications/slack-add-user-channel.application.spec.ts
backend/src/modules/communication/applications/slack-add-user-channel.application.ts
backend/src/modules/communication/applications/slack-archive-channel.application.spec.ts
backend/src/modules/communication/applications/slack-communication.application.spec.ts
backend/src/modules/communication/applications/slack-merge-board-application.spec.ts
backend/src/modules/communication/applications/slack-responsible.application.spec.ts

Relates to:
- #1255 
-Add tests to communication applications
- #1255

test: communication applications tests

---

backend/src/modules/boards/services/update.board.service.ts

Relates to:
- #1288 
Fixes:
-  The cards that have the "\n" doesn't stay aligned as points of a list
-  The cards with multiple "\n" have multiple new lines in the slack message
- Multiple \n are replaced with only one \n
- After a \n it is introduced a \t for spacing and alignment 
This pull request closes #1288

fix: submitted action points format

---

backend/src/modules/boards/applications/duplicate-board.use-case.ts
frontend/src/components/CreateBoard/SplitBoard/SubTeamsTab/UsersBox/index.tsx

- Team can be optional when duplicating a board
- Fix the size of the selected participant's box in the regular board creation page

fix: duplicate board without team

---

frontend/src/pages/boards/[boardId]/index.tsx

Fixes:
- #1317
- Wrap `getPublicStatusRequest` inside the existing try-catch, as it will redirect the user to the proper page based on the session.
This pull request closes #1317

fix: board not found redirect

---

frontend/.eslintrc.cjs
frontend/.storybook/main.js
frontend/tsconfig.json

| Old                                                                                                                                        | New                                                                                                                                        |
|--------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------|
| <img width="1173" alt="image" src="https://user-images.githubusercontent.com/61988699/232013373-27f3b704-e9fc-495a-a848-b732ddb3e1e9.png"> | <img width="1173" alt="image" …

fix: tsconfig paths

---

frontend/src/components/Board/Settings/index.tsx

Relates to:
- #1455
Fixes:
- #1455
- Remove scheduling option from board settings
This pull request closes #1455

fix: remove scheduling from board settings

---

frontend/src/components/CardBoard/CardBody/CardBody.tsx
frontend/src/components/Users/UsersList/UsersList.tsx
frontend/src/components/layouts/Layout/styles.tsx

Fixes:
- #1454
| Old                                                                                                             | New                                                                                                             |
|-----------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|
| ![image](https://user-images.githubusercontent.com/61988699/235931690-a6121d50-f64e-4713-af48-fde116fd401f.png) | ![image](https://user-images.githubusercontent.com/61988699/235931802-deff7a16-4f37-444e-865c-1fe88eb0c496.png) |
| ![image](https://user-images.githubusercontent.com/61988699/235931600-d6731fa1-1f9c-4a8a-af48 …

fix: scroll on boards list

---

frontend/src/components/Board/SplitBoard/Header/index.tsx

Relates to:
- #1323
Fixes:
- #1323
- adding the `eventPreventDefault` on the `onOpenAutoFocus` prop
This pull request closes #1323

fix: popover border in main board

---

backend/src/infrastructure/database/mongoose.module.ts
backend/src/infrastructure/database/plugins/soft-delete-not-mocked.plugin.spec.ignore.ts
backend/src/infrastructure/database/plugins/soft-delete.plugin.ts
backend/src/modules/boardUsers/interfaces/repositories/board-user.repository.interface.ts
backend/src/modules/boardUsers/interfaces/services/delete.board.user.service.interface.ts
backend/src/modules/boardUsers/interfaces/services/get.board.user.service.interface.ts
backend/src/modules/boardUsers/repositories/board-user.repository.ts
backend/src/modules/boardUsers/services/delete.board.user.service.ts
backend/src/modules/boardUsers/services/get.board.user.service.ts
backend/src/modules/boards/repositories/board.repository.ts
backend/src/modules/boards/utils/populate-board.ts
backend/src/modules/users/applications/delete-user.use-case.spec.ts
backend/src/modules/users/applications/delete-user.use-case.ts
backend/src/modules/users/applications/soft-delete-user.use-case.spec.ts
backend/src/modules/users/repository/user.repository.interface.ts
backend/src/modules/users/repository/user.repository.ts
backend/src/modules/users/users.module.ts

Relates to:
- #945 
- Add Soft-delete mongoose plugin (can be used for other schemas)
- Add soft-delete plugin to User Schema
- Remove user from not submitted boards only, to maintain history
- All the query's consider `isDeleted` field to not present data when it's `true`, unless the query specifies their presentation
- Delete-user-case now also deletes the user from the open boards
@nunocaseiro 
This pull request closes #945

feat: issue 945 soft delete users

---

backend/.env.example
backend/package-lock.json
backend/src/infrastructure/config/config.module.ts
backend/src/modules/azure/azure.module.ts
backend/src/modules/azure/schedules/synchronize-ad-users.cron.azure.use-case.spec.ts
backend/src/modules/azure/schedules/synchronize-ad-users.cron.azure.use-case.ts
backend/src/modules/teamUsers/teamusers.module.ts
backend/src/modules/teams/applications/get-team-by-name.use-case.spec.ts
backend/src/modules/teams/applications/get-team-by-name.use-case.ts
backend/src/modules/teams/constants.ts
backend/src/modules/teams/interfaces/repositories/team.repository.interface.ts
backend/src/modules/teams/interfaces/services/get.team.service.interface.ts
backend/src/modules/teams/providers.ts
backend/src/modules/teams/repositories/team.repository.ts
backend/src/modules/teams/services/get.team.service.spec.ts
backend/src/modules/teams/services/get.team.service.ts
backend/src/modules/teams/teams.module.ts
backend/src/modules/users/interfaces/services/create.user.service.interface.ts
backend/src/modules/users/services/create.user.service.spec.ts
backend/src/modules/users/services/create.user.service.ts

Relates to:
- #1601 
- Automatically add's new users to a team defined in env vars during AD-App users synchronization cron job
- Changes insertion of users from each one to a user batch
This pull request closes #1601

feat:  automatically add users to team during synchronization
